// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"confluence-mcp/pkg/helpers"
	"context"
	"github.com/mark3labs/mcp-go/mcp"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ByOperation tool
const ByOperationInputSchema = "{\n  \"properties\": {\n    \"expand\": {\n      \"description\": \"A comma separated list of properties to expand on the content properties. Default value: group.\",\n      \"type\": \"string\"\n    },\n    \"id\": {\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"id\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the ByOperation tool (Status: 200, Content-Type: application/json)
const ByOperationResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Returns a JSON representation of the restrictions group by operations.\n\n## Response Structure\n\n- Structure (Type: unknown):\n"

// NewByOperationMCPTool creates the MCP Tool instance for ByOperation
func NewByOperationMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ByOperation",
		"Get all restrictions by Operation - Returns info about all restrictions by operation.",
		[]byte(ByOperationInputSchema),
	)
}

// ByOperationHandler is the handler function for the ByOperation tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ByOperationHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/confluence/rest/api/content/{id}/restriction/byOperation", args, []string{"id"}, contentType, "ByOperation")
}
