// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"confluence-mcp/pkg/helpers"
	"context"
	"github.com/mark3labs/mcp-go/mcp"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateSpaceRestoreJob tool
const CreateSpaceRestoreJobInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"description\": \"space restore settings\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the CreateSpaceRestoreJob tool (Status: 200, Content-Type: application/json)
const CreateSpaceRestoreJobResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Returns a JSON representation of the space restore job.\n\n## Response Structure\n\n- Structure (Type: unknown):\n"

// Response Template for the CreateSpaceRestoreJob tool (Status: 400, Content-Type: application/json)
const CreateSpaceRestoreJobResponseTemplate_B = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 400\n\n**Content-Type:** application/json\n\n>  Returned if invalid filename provided\n\n## Response Structure\n\n- Structure (Type: unknown):\n"

// Response Template for the CreateSpaceRestoreJob tool (Status: 403, Content-Type: application/json)
const CreateSpaceRestoreJobResponseTemplate_C = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 403\n\n**Content-Type:** application/json\n\n> Returned if user doesn't have permission to restore spaces\n\n## Response Structure\n\n- Structure (Type: unknown):\n"

// NewCreateSpaceRestoreJobMCPTool creates the MCP Tool instance for CreateSpaceRestoreJob
func NewCreateSpaceRestoreJobMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateSpaceRestoreJob",
		"Create space restore job - Creates new space restore job and adds it to the queue.",
		[]byte(CreateSpaceRestoreJobInputSchema),
	)
}

// CreateSpaceRestoreJobHandler is the handler function for the CreateSpaceRestoreJob tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateSpaceRestoreJobHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/confluence/rest/api/backup-restore/restore/space", args, []string{}, contentType, "CreateSpaceRestoreJob")
}
