// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"confluence-mcp/pkg/helpers"
	"context"
	"github.com/mark3labs/mcp-go/mcp"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateSiteRestoreJobForUploadedBackupFile tool
const CreateSiteRestoreJobForUploadedBackupFileInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"description\": \"Backup file to be uploaded. Has to be a zip file.\",\n      \"properties\": {\n        \"file\": {\n          \"description\": \"backup file uploaded. Has to be a zip file.\",\n          \"type\": \"string\"\n        }\n      },\n      \"type\": \"object\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the CreateSiteRestoreJobForUploadedBackupFile tool (Status: 200, Content-Type: application/json)
const CreateSiteRestoreJobForUploadedBackupFileResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Returns a JSON representation of the site restore job details.\n\n## Response Structure\n\n- Structure (Type: unknown):\n"

// Response Template for the CreateSiteRestoreJobForUploadedBackupFile tool (Status: 400, Content-Type: application/json)
const CreateSiteRestoreJobForUploadedBackupFileResponseTemplate_B = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 400\n\n**Content-Type:** application/json\n\n>  Returned if the uploaded file is not a zip file\n\n## Response Structure\n\n- Structure (Type: unknown):\n"

// Response Template for the CreateSiteRestoreJobForUploadedBackupFile tool (Status: 403, Content-Type: application/json)
const CreateSiteRestoreJobForUploadedBackupFileResponseTemplate_C = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 403\n\n**Content-Type:** application/json\n\n>  Returned if user doesn't have permission to restore space\n\n## Response Structure\n\n- Structure (Type: unknown):\n"

// NewCreateSiteRestoreJobForUploadedBackupFileMCPTool creates the MCP Tool instance for CreateSiteRestoreJobForUploadedBackupFile
func NewCreateSiteRestoreJobForUploadedBackupFileMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateSiteRestoreJobForUploadedBackupFile",
		"Create site restore job for upload backup file - This resource expects a multipart post. The media-type multipart/form-data is defined in RFC 1867. \n\nMost client libraries have classes that make dealing with multipart posts simple. \n\nFor instance, in Java the Apache HTTP Components library provides a MultiPartEntity that makes it simple to submit a multipart POST. \n\n In order to protect against XSRF attacks, because this method accepts multipart/form-data, it has XSRF protection on it.  This means you must submit a header of X-Atlassian-Token: nocheck with the request, otherwise it will be blocked. \n\n The name of the multipart/form-data parameter that contains attachments must be \"file\". \n\n An example to attach the file: \n\n curl -D- -u admin:admin -X POST -H \"X-Atlassian-Token: nocheck\" -F  file=@myfile.zip http://myhost/rest/api/backup-restore/restore/space/upload \n\n.",
		[]byte(CreateSiteRestoreJobForUploadedBackupFileInputSchema),
	)
}

// CreateSiteRestoreJobForUploadedBackupFileHandler is the handler function for the CreateSiteRestoreJobForUploadedBackupFile tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateSiteRestoreJobForUploadedBackupFileHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	fileName := ""
	if fn, ok := args["file_name"]; ok {
		if s, ok := fn.(string); ok {
			fileName = s
		}
	}
	if fileName == "" {
		return mcp.NewToolResultError("missing required argument: file_name"), nil
	}
	fileContentBase64 := ""
	if fc, ok := args["file_content"]; ok {
		if s, ok := fc.(string); ok {
			fileContentBase64 = s
		}
	}
	return mcputils.ForwardUploadRequest(ctx, upstream, "POST", "/confluence/rest/api/backup-restore/restore/site/upload", fileName, fileContentBase64, "multipart/form-data", "CreateSiteRestoreJobForUploadedBackupFile")
}
