// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"confluence-mcp/pkg/helpers"
	"context"
	"github.com/mark3labs/mcp-go/mcp"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ForOperation tool
const ForOperationInputSchema = "{\n  \"properties\": {\n    \"expand\": {\n      \"description\": \"Aa comma separated list of properties to expand on the content properties. Default value: group.\",\n      \"type\": \"string\"\n    },\n    \"id\": {\n      \"type\": \"string\"\n    },\n    \"limit\": {\n      \"default\": 100,\n      \"description\": \"pagination limit.\",\n      \"format\": \"int32\",\n      \"type\": \"integer\"\n    },\n    \"operationKey\": {\n      \"description\": \"key of the operation.\",\n      \"type\": \"string\"\n    },\n    \"start\": {\n      \"description\": \"pagination start.\",\n      \"format\": \"int32\",\n      \"type\": \"integer\"\n    }\n  },\n  \"required\": [\n    \"id\",\n    \"operationKey\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the ForOperation tool (Status: 200, Content-Type: application/json)
const ForOperationResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Returns a JSON representation of the restrictions of given operation.\n\n## Response Structure\n\n- Structure (Type: unknown):\n"

// NewForOperationMCPTool creates the MCP Tool instance for ForOperation
func NewForOperationMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ForOperation",
		"Get all restrictions for given operation - Returns info about all restrictions of given operation.",
		[]byte(ForOperationInputSchema),
	)
}

// ForOperationHandler is the handler function for the ForOperation tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ForOperationHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/confluence/rest/api/content/{id}/restriction/byOperation/{operationKey}", args, []string{"id", "operationKey"}, contentType, "ForOperation")
}
