// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"confluence-mcp/pkg/helpers"
	"context"
	"github.com/mark3labs/mcp-go/mcp"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetAllSpacePermissions tool
const GetAllSpacePermissionsInputSchema = "{\n  \"properties\": {\n    \"spaceKey\": {\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"spaceKey\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetAllSpacePermissions tool (Status: 200, Content-Type: application/json)
const GetAllSpacePermissionsResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Returns a JSON representation of all permissions granted to users/groups/anonymous user in specified space.\n\n## Response Structure\n\n- Structure (Type: array):\n  - **Items** (Type: object):\n    - **operation** (Type: object):\n      - **operationKey** (Type: string):\n          - Example: 'read'\n      - **targetType** (Type: string):\n          - Example: 'space'\n    - **spaceId** (Type: integer, int64):\n    - **spaceKey** (Type: string):\n    - **subject** (Type: unknown):\n"

// Response Template for the GetAllSpacePermissions tool (Status: 401, Content-Type: application/json)
const GetAllSpacePermissionsResponseTemplate_B = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 401\n\n**Content-Type:** application/json\n\n> Returned if the calling User is not authenticated.\n\n## Response Structure\n\n- Structure (Type: unknown):\n"

// Response Template for the GetAllSpacePermissions tool (Status: 403, Content-Type: application/json)
const GetAllSpacePermissionsResponseTemplate_C = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 403\n\n**Content-Type:** application/json\n\n> Returned if the calling User does not have necessary permission.\n\n## Response Structure\n\n- Structure (Type: unknown):\n"

// NewGetAllSpacePermissionsMCPTool creates the MCP Tool instance for GetAllSpacePermissions
func NewGetAllSpacePermissionsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetAllSpacePermissions",
		"Get all space permissions - Returns list of permissions granted to users and groups in the particular space.\n\nExample request URI's:\n"+"\x60"+"https://example.com/confluence/rest/api/space/TESTSPACE/permissions"+"\x60"+"",
		[]byte(GetAllSpacePermissionsInputSchema),
	)
}

// GetAllSpacePermissionsHandler is the handler function for the GetAllSpacePermissions tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetAllSpacePermissionsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/confluence/rest/api/space/{spaceKey}/permissions", args, []string{"spaceKey"}, contentType, "GetAllSpacePermissions")
}
