// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"confluence-mcp/pkg/helpers"
	"context"
	"github.com/mark3labs/mcp-go/mcp"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetAccessModeStatus tool
const GetAccessModeStatusInputSchema = "{\n  \"type\": \"object\"\n}"

// NewGetAccessModeStatusMCPTool creates the MCP Tool instance for GetAccessModeStatus
func NewGetAccessModeStatusMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetAccessModeStatus",
		"Get access mode status - Returns the access mode status for Confluence.",
		[]byte(GetAccessModeStatusInputSchema),
	)
}

// GetAccessModeStatusHandler is the handler function for the GetAccessModeStatus tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetAccessModeStatusHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/confluence/rest/api/accessmode", args, []string{}, contentType, "GetAccessModeStatus")
}
