// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"confluence-mcp/pkg/helpers"
	"context"
	"github.com/mark3labs/mcp-go/mcp"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetDefaultColorScheme tool
const GetDefaultColorSchemeInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the GetDefaultColorScheme tool (Status: 200, Content-Type: application/json)
const GetDefaultColorSchemeResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Returns a full JSON representation of color scheme including light and dark theme\n\n## Response Structure\n\n- Structure (Type: unknown):\n"

// NewGetDefaultColorSchemeMCPTool creates the MCP Tool instance for GetDefaultColorScheme
func NewGetDefaultColorSchemeMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetDefaultColorScheme",
		"Get default global color scheme - Get default color scheme for the instance\n\n",
		[]byte(GetDefaultColorSchemeInputSchema),
	)
}

// GetDefaultColorSchemeHandler is the handler function for the GetDefaultColorScheme tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetDefaultColorSchemeHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/confluence/rest/api/color-scheme/default", args, []string{}, contentType, "GetDefaultColorScheme")
}
