// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"confluence-mcp/pkg/helpers"
	"context"
	"github.com/mark3labs/mcp-go/mcp"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetGlobalColorScheme tool
const GetGlobalColorSchemeInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the GetGlobalColorScheme tool (Status: 200, Content-Type: application/json)
const GetGlobalColorSchemeResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Returns a full JSON representation of color scheme including light and dark theme\n\n## Response Structure\n\n- Structure (Type: unknown):\n"

// NewGetGlobalColorSchemeMCPTool creates the MCP Tool instance for GetGlobalColorScheme
func NewGetGlobalColorSchemeMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetGlobalColorScheme",
		"Get global color scheme - Get information about the current color scheme for the instance\n\n",
		[]byte(GetGlobalColorSchemeInputSchema),
	)
}

// GetGlobalColorSchemeHandler is the handler function for the GetGlobalColorScheme tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetGlobalColorSchemeHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/confluence/rest/api/color-scheme", args, []string{}, contentType, "GetGlobalColorScheme")
}
