// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"confluence-mcp/pkg/helpers"
	"context"
	"github.com/mark3labs/mcp-go/mcp"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the Index2 tool
const Index2InputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the Index2 tool (Status: 200, Content-Type: application/json)
const Index2ResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> The server build information.\n\n## Response Structure\n\n- Structure (Type: unknown):\n"

// Response Template for the Index2 tool (Status: 401, Content-Type: application/json)
const Index2ResponseTemplate_B = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 401\n\n**Content-Type:** application/json\n\n> Returned if the calling User is not authenticated.\n\n## Response Structure\n\n- Structure (Type: unknown):\n"

// NewIndex2MCPTool creates the MCP Tool instance for Index2
func NewIndex2MCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"Index2",
		"Get server information - Returns information about the current application build running on this instance.",
		[]byte(Index2InputSchema),
	)
}

// Index2Handler is the handler function for the Index2 tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func Index2Handler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/confluence/rest/api/server-information", args, []string{}, contentType, "Index2")
}
