// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"confluence-mcp/pkg/helpers"
	"context"
	"github.com/mark3labs/mcp-go/mcp"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the RevokePermissionsFromGroup1 tool
const RevokePermissionsFromGroup1InputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"items\": {\n        \"properties\": {\n          \"operationKey\": {\n            \"example\": \"read\",\n            \"type\": \"string\"\n          },\n          \"targetType\": {\n            \"example\": \"space\",\n            \"type\": \"string\"\n          }\n        },\n        \"type\": \"object\"\n      },\n      \"type\": \"array\"\n    },\n    \"groupName\": {\n      \"type\": \"string\"\n    },\n    \"spaceKey\": {\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"groupName\",\n    \"spaceKey\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the RevokePermissionsFromGroup1 tool (Status: 400, Content-Type: application/json)
const RevokePermissionsFromGroup1ResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 400\n\n**Content-Type:** application/json\n\n> Returned if incorrect permissions are passed in request (for e.g. non existing operation or global permission).\n\n## Response Structure\n\n- Structure (Type: unknown):\n"

// Response Template for the RevokePermissionsFromGroup1 tool (Status: 401, Content-Type: application/json)
const RevokePermissionsFromGroup1ResponseTemplate_B = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 401\n\n**Content-Type:** application/json\n\n> Returned if the calling User is not authenticated.\n\n## Response Structure\n\n- Structure (Type: unknown):\n"

// Response Template for the RevokePermissionsFromGroup1 tool (Status: 403, Content-Type: application/json)
const RevokePermissionsFromGroup1ResponseTemplate_C = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 403\n\n**Content-Type:** application/json\n\n> Returned if the calling User does not have necessary permission.\n\n## Response Structure\n\n- Structure (Type: unknown):\n"

// Response Template for the RevokePermissionsFromGroup1 tool (Status: 404, Content-Type: application/json)
const RevokePermissionsFromGroup1ResponseTemplate_D = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 404\n\n**Content-Type:** application/json\n\n> Returned if group with specified key not found.\n\n## Response Structure\n\n- Structure (Type: unknown):\n"

// NewRevokePermissionsFromGroup1MCPTool creates the MCP Tool instance for RevokePermissionsFromGroup1
func NewRevokePermissionsFromGroup1MCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"RevokePermissionsFromGroup1",
		"Revoke space permissions from a group - Revoke permissions from a group in the given space.\nIf group doesn't have permissions that we are trying to revoke, those permissions will be silently skipped.\nMultiple permissions could be passed in one request. Supported targetType and operationKey pairs:\n* space read\n* space administer\n* space export\n* space restrict\n* space delete_own\n* space delete_mail\n* page create\n* page delete\n* blogpost create\n* blogpost delete\n* comment create\n* comment delete\n* attachment create\n* attachment delete\n\nSee <a href=\"https://confluence.atlassian.com/display/DOC/Space+Permissions+Overview\">Space Permissions documentation</a> for additional information about supported permissions.\n\nExample request URI's:\n"+"\x60"+"https://example.com/confluence/rest/api/space/TESTSPACE/permissions/group/test-group-name/revoke"+"\x60"+"",
		[]byte(RevokePermissionsFromGroup1InputSchema),
	)
}

// RevokePermissionsFromGroup1Handler is the handler function for the RevokePermissionsFromGroup1 tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func RevokePermissionsFromGroup1Handler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/confluence/rest/api/space/{spaceKey}/permissions/group/{groupName}/revoke", args, []string{"groupName", "spaceKey"}, contentType, "RevokePermissionsFromGroup1")
}
