// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"confluence-mcp/pkg/helpers"
	"context"
	"github.com/mark3labs/mcp-go/mcp"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the TestWebhook tool
const TestWebhookInputSchema = "{\n  \"properties\": {\n    \"url\": {\n      \"description\": \"the url in which to connect to\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"url\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the TestWebhook tool (Status: 401, Content-Type: application/json)
const TestWebhookResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 401\n\n**Content-Type:** application/json\n\n> returned if the currently authenticated user has insufficient permissions to test a connection.\n\n## Response Structure\n\n- Structure (Type: unknown):\n"

// Response Template for the TestWebhook tool (Status: 404, Content-Type: application/json)
const TestWebhookResponseTemplate_B = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 404\n\n**Content-Type:** application/json\n\n> returned if repository does not exist.\n\n## Response Structure\n\n- Structure (Type: unknown):\n"

// NewTestWebhookMCPTool creates the MCP Tool instance for TestWebhook
func NewTestWebhookMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"TestWebhook",
		"Test webhook - Test connectivity to a specific endpoint. The authenticated user must be an administrator to call this resource.",
		[]byte(TestWebhookInputSchema),
	)
}

// TestWebhookHandler is the handler function for the TestWebhook tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func TestWebhookHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/confluence/rest/api/webhooks/test", args, []string{}, contentType, "TestWebhook")
}
