// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"confluence-mcp/pkg/helpers"
	"context"
	"github.com/mark3labs/mcp-go/mcp"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UnIndexAll tool
const UnIndexAllInputSchema = "{\n  \"type\": \"object\"\n}"

// NewUnIndexAllMCPTool creates the MCP Tool instance for UnIndexAll
func NewUnIndexAllMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UnIndexAll",
		"Remove all content from search index - Removes all content from the search index, effectively clearing the entire search index.\nThis operation is destructive and will require a full reindex to restore search functionality.\nThis operation is only available to system administrators.\n\n**Warning**: This operation will remove all searchable content from the index.\nUsers will not be able to search for content until a reindex is performed.\n\nExample request URI:\n"+"\x60"+"http://example.com/confluence/rest/api/index/unindex"+"\x60"+"\n",
		[]byte(UnIndexAllInputSchema),
	)
}

// UnIndexAllHandler is the handler function for the UnIndexAll tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UnIndexAllHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/confluence/rest/api/index/unindex", args, []string{}, contentType, "UnIndexAll")
}
