// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"confluence-mcp/pkg/helpers"
	"context"
	"github.com/mark3labs/mcp-go/mcp"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the Update5 tool
const Update5InputSchema = "{\n  \"properties\": {\n    \"groupName\": {\n      \"description\": \"The group name identifying the given group.\",\n      \"type\": \"string\"\n    },\n    \"username\": {\n      \"description\": \"The username identifying the given user.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"groupName\",\n    \"username\"\n  ],\n  \"type\": \"object\"\n}"

// NewUpdate5MCPTool creates the MCP Tool instance for Update5
func NewUpdate5MCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"Update5",
		"Update user group - Add the given User identified by username to the given Group identified by groupName. \n\nThis method is idempotent i.e., if the membership already exists then no action will be taken.",
		[]byte(Update5InputSchema),
	)
}

// Update5Handler is the handler function for the Update5 tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func Update5Handler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/confluence/rest/api/user/{username}/group/{groupName}", args, []string{"groupName", "username"}, contentType, "Update5")
}
