// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"fmt"
	"github.com/mark3labs/mcp-go/mcp"
	"io"
	"sonarqube-mcp/pkg/helpers"
	"time"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetProjectAnalysesSearch tool
const GetProjectAnalysesSearchInputSchema = "{\n  \"properties\": {\n    \"branch\": {\n      \"description\": \"Key of a branch\",\n      \"type\": \"string\"\n    },\n    \"category\": {\n      \"description\": \"Event category. Filter analyses that have at least one event of the category specified.\",\n      \"enum\": [\n        \"VERSION\",\n        \"OTHER\",\n        \"QUALITY_PROFILE\",\n        \"QUALITY_GATE\",\n        \"DEFINITION_CHANGE\",\n        \"ISSUE_DETECTION\",\n        \"SQ_UPGRADE\"\n      ],\n      \"type\": \"string\"\n    },\n    \"from\": {\n      \"description\": \"Filter analyses created after the given date (inclusive). Either a date (server timezone) or datetime can be provided\",\n      \"type\": \"string\"\n    },\n    \"p\": {\n      \"default\": \"1\",\n      \"description\": \"1-based page number\",\n      \"type\": \"string\"\n    },\n    \"project\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    },\n    \"ps\": {\n      \"description\": \"Page size. Must be greater than 0 and less or equal than 500\",\n      \"maximum\": 500,\n      \"type\": \"integer\"\n    },\n    \"statuses\": {\n      \"description\": \"List of statuses of desired analysis.\",\n      \"enum\": [\n        \"P\",\n        \"U\",\n        \"L\"\n      ],\n      \"type\": \"string\"\n    },\n    \"to\": {\n      \"description\": \"Filter analyses created before the given date (inclusive). Either a date (server timezone) or datetime can be provided\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"project\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetProjectAnalysesSearch tool (Status: 200, Content-Type: application/json)
const GetProjectAnalysesSearchResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetProjectAnalysesSearchMCPTool creates the MCP Tool instance for GetProjectAnalysesSearch
func NewGetProjectAnalysesSearchMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetProjectAnalysesSearch",
		"Search a project analyses and attached events. - Search a project analyses and attached events. Requires the following permission: 'Browse' on the specified project. For applications, it also requires 'Browse' permission on its child projects.",
		[]byte(GetProjectAnalysesSearchInputSchema),
	)
}

// GetProjectAnalysesSearchHandler is the handler function for the GetProjectAnalysesSearch tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetProjectAnalysesSearchHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	startTime := time.Now()
	resp, err := mcputils.ForwardRequest(ctx, upstream, "GET", "/api/project_analyses/search", args, []string{}, contentType)
	if err != nil {
		return nil, fmt.Errorf("upstream request failed: %w", err)
	}
	defer resp.Body.Close()

	mcputils.LogResponse(ctx, resp.StatusCode, "GET", resp.Request.URL.String(), time.Since(startTime), nil)

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return mcp.NewToolResultError(fmt.Sprintf("upstream error: status %d, body: %s", resp.StatusCode, string(body))), nil
	}

	if mcputils.IsBinaryDownload(resp) {
		filePath, written, err := mcputils.SaveBinaryStream(resp, "GetProjectAnalysesSearch")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		return mcp.NewToolResultText(fmt.Sprintf("Saved to: %s (%d bytes)", filePath, written)), nil
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read upstream response: %w", err)
	}

	mcputils.LogResponse(ctx, resp.StatusCode, "GET", resp.Request.URL.String(), time.Since(startTime), body)

	return mcp.NewToolResultText(string(body)), nil
}
