// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"fmt"
	"github.com/mark3labs/mcp-go/mcp"
	"io"
	"sonarqube-mcp/pkg/helpers"
	"time"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetSettingsListDefinitions tool
const GetSettingsListDefinitionsInputSchema = "{\n  \"properties\": {\n    \"component\": {\n      \"description\": \"Component key\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the GetSettingsListDefinitions tool (Status: 200, Content-Type: application/json)
const GetSettingsListDefinitionsResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetSettingsListDefinitionsMCPTool creates the MCP Tool instance for GetSettingsListDefinitions
func NewGetSettingsListDefinitionsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetSettingsListDefinitions",
		"List settings definitions. - List settings definitions. Requires 'Browse' permission when a component is specified To access licensed settings, authentication is required To access secured settings, one of the following permissions is required: - 'Execute Analysis' - 'Administer System' - 'Administer' rights on the specified component",
		[]byte(GetSettingsListDefinitionsInputSchema),
	)
}

// GetSettingsListDefinitionsHandler is the handler function for the GetSettingsListDefinitions tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetSettingsListDefinitionsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	startTime := time.Now()
	resp, err := mcputils.ForwardRequest(ctx, upstream, "GET", "/api/settings/list_definitions", args, []string{}, contentType)
	if err != nil {
		return nil, fmt.Errorf("upstream request failed: %w", err)
	}
	defer resp.Body.Close()

	mcputils.LogResponse(ctx, resp.StatusCode, "GET", resp.Request.URL.String(), time.Since(startTime), nil)

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return mcp.NewToolResultError(fmt.Sprintf("upstream error: status %d, body: %s", resp.StatusCode, string(body))), nil
	}

	if mcputils.IsBinaryDownload(resp) {
		filePath, written, err := mcputils.SaveBinaryStream(resp, "GetSettingsListDefinitions")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		return mcp.NewToolResultText(fmt.Sprintf("Saved to: %s (%d bytes)", filePath, written)), nil
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read upstream response: %w", err)
	}

	mcputils.LogResponse(ctx, resp.StatusCode, "GET", resp.Request.URL.String(), time.Since(startTime), body)

	return mcp.NewToolResultText(string(body)), nil
}
