// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"fmt"
	"github.com/mark3labs/mcp-go/mcp"
	"io"
	"sonarqube-mcp/pkg/helpers"
	"time"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetUserGroupsSearch tool
const GetUserGroupsSearchInputSchema = "{\n  \"properties\": {\n    \"f\": {\n      \"description\": \"Comma-separated list of the fields to be returned in response. All the fields are returned by default.\",\n      \"enum\": [\n        \"name\",\n        \"description\",\n        \"membersCount\",\n        \"managed\"\n      ],\n      \"type\": \"string\"\n    },\n    \"managed\": {\n      \"description\": \"Return managed or non-managed groups. Only available for managed instances, throws for non-managed instances.\",\n      \"enum\": [\n        \"true\",\n        \"false\",\n        \"yes\",\n        \"no\"\n      ],\n      \"type\": \"string\"\n    },\n    \"p\": {\n      \"default\": \"1\",\n      \"description\": \"1-based page number\",\n      \"type\": \"string\"\n    },\n    \"ps\": {\n      \"description\": \"Page size. Must be greater than 0 and less or equal than 500\",\n      \"maximum\": 500,\n      \"type\": \"integer\"\n    },\n    \"q\": {\n      \"description\": \"Limit search to names that contain the supplied string.\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the GetUserGroupsSearch tool (Status: 200, Content-Type: application/json)
const GetUserGroupsSearchResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetUserGroupsSearchMCPTool creates the MCP Tool instance for GetUserGroupsSearch
func NewGetUserGroupsSearchMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetUserGroupsSearch",
		"Search for user groups. - Search for user groups. Requires the following permission: 'Administer System'.",
		[]byte(GetUserGroupsSearchInputSchema),
	)
}

// GetUserGroupsSearchHandler is the handler function for the GetUserGroupsSearch tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetUserGroupsSearchHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	startTime := time.Now()
	resp, err := mcputils.ForwardRequest(ctx, upstream, "GET", "/api/user_groups/search", args, []string{}, contentType)
	if err != nil {
		return nil, fmt.Errorf("upstream request failed: %w", err)
	}
	defer resp.Body.Close()

	mcputils.LogResponse(ctx, resp.StatusCode, "GET", resp.Request.URL.String(), time.Since(startTime), nil)

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return mcp.NewToolResultError(fmt.Sprintf("upstream error: status %d, body: %s", resp.StatusCode, string(body))), nil
	}

	if mcputils.IsBinaryDownload(resp) {
		filePath, written, err := mcputils.SaveBinaryStream(resp, "GetUserGroupsSearch")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		return mcp.NewToolResultText(fmt.Sprintf("Saved to: %s (%d bytes)", filePath, written)), nil
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read upstream response: %w", err)
	}

	mcputils.LogResponse(ctx, resp.StatusCode, "GET", resp.Request.URL.String(), time.Since(startTime), body)

	return mcp.NewToolResultText(string(body)), nil
}
