// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"fmt"
	"github.com/mark3labs/mcp-go/mcp"
	"io"
	"sonarqube-mcp/pkg/helpers"
	"time"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostHotspotsEditComment tool
const PostHotspotsEditCommentInputSchema = "{\n  \"properties\": {\n    \"comment\": {\n      \"description\": \"Comment key\",\n      \"type\": \"string\"\n    },\n    \"text\": {\n      \"description\": \"Comment text\",\n      \"maxLength\": 1000,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"comment\",\n    \"text\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the PostHotspotsEditComment tool (Status: 200, Content-Type: application/json)
const PostHotspotsEditCommentResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewPostHotspotsEditCommentMCPTool creates the MCP Tool instance for PostHotspotsEditComment
func NewPostHotspotsEditCommentMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostHotspotsEditComment",
		"Edit a comment. - Edit a comment. Requires authentication and the following permission: 'Browse' on the project of the specified hotspot.",
		[]byte(PostHotspotsEditCommentInputSchema),
	)
}

// PostHotspotsEditCommentHandler is the handler function for the PostHotspotsEditComment tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostHotspotsEditCommentHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	startTime := time.Now()
	resp, err := mcputils.ForwardRequest(ctx, upstream, "POST", "/api/hotspots/edit_comment", args, []string{}, contentType)
	if err != nil {
		return nil, fmt.Errorf("upstream request failed: %w", err)
	}
	defer resp.Body.Close()

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), nil)

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return mcp.NewToolResultError(fmt.Sprintf("upstream error: status %d, body: %s", resp.StatusCode, string(body))), nil
	}

	if mcputils.IsBinaryDownload(resp) {
		filePath, written, err := mcputils.SaveBinaryStream(resp, "PostHotspotsEditComment")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		return mcp.NewToolResultText(fmt.Sprintf("Saved to: %s (%d bytes)", filePath, written)), nil
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read upstream response: %w", err)
	}

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), body)

	return mcp.NewToolResultText(string(body)), nil
}
