// Code generated by https://github.com/wl4g-ai/mcpgen-go

package mcptools

import (
	"context"
	"fmt"
	"github.com/mark3labs/mcp-go/mcp"
	"io"
	"sonarqube-mcp/pkg/helpers"
	"time"
)

// Code generated by https://github.com/wl4g-ai/mcpgen-go

// Input Schema for the PostIssuesAnticipatedTransitions tool
const PostIssuesAnticipatedTransitionsInputSchema = "{\n  \"properties\": {\n    \"projectKey\": {\n      \"description\": \"The key of the project\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"projectKey\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostIssuesAnticipatedTransitionsMCPTool creates the MCP Tool instance for PostIssuesAnticipatedTransitions
func NewPostIssuesAnticipatedTransitionsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostIssuesAnticipatedTransitions",
		"Receive a list of anticipated transitions that can be applied to not yet discovered issues on a specific project. - Receive a list of anticipated transitions that can be applied to not yet discovered issues on a specific project. \nRequires the following permission: 'Administer Issues' on the specified project. \nOnly falsepositive, wontfix and accept transitions are supported. \nUpon successful execution, the HTTP status code returned is 202 (Accepted). \nRequest example:\n[\n {\n \"ruleKey\": \"squid:S0001\",\n \"issueMessage\": \"issueMessage1\",\n \"filePath\": \"filePath1\",\n \"line\": 1,\n \"lineHash\": \"lineHash1\",\n \"transition\": \"falsepositive\",\n \"comment\": \"comment1\"\n },\n {\n \"ruleKey\": \"squid:S0002\",\n \"issueMessage\": \"issueMessage2\",\n \"filePath\": \"filePath2\",\n \"line\": 2,\n \"lineHash\": \"lineHash2\",\n \"transition\": \"wontfix\",\n \"comment\": \"comment2\"\n }\n]",
		[]byte(PostIssuesAnticipatedTransitionsInputSchema),
	)
}

// PostIssuesAnticipatedTransitionsHandler is the handler function for the PostIssuesAnticipatedTransitions tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostIssuesAnticipatedTransitionsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	startTime := time.Now()
	resp, err := mcputils.ForwardRequest(ctx, upstream, "POST", "/api/issues/anticipated_transitions", args, []string{}, contentType)
	if err != nil {
		return nil, fmt.Errorf("upstream request failed: %w", err)
	}
	defer resp.Body.Close()

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), nil)

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return mcp.NewToolResultError(fmt.Sprintf("upstream error: status %d, body: %s", resp.StatusCode, string(body))), nil
	}

	if mcputils.IsBinaryDownload(resp) {
		filePath, written, err := mcputils.SaveBinaryStream(resp, "PostIssuesAnticipatedTransitions")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		return mcp.NewToolResultText(fmt.Sprintf("Saved to: %s (%d bytes)", filePath, written)), nil
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read upstream response: %w", err)
	}

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), body)

	return mcp.NewToolResultText(string(body)), nil
}
