// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"fmt"
	"github.com/mark3labs/mcp-go/mcp"
	"io"
	"sonarqube-mcp/pkg/helpers"
	"time"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostWebhooksCreate tool
const PostWebhooksCreateInputSchema = "{\n  \"properties\": {\n    \"name\": {\n      \"description\": \"Name displayed in the administration console of webhooks\",\n      \"maxLength\": 100,\n      \"type\": \"string\"\n    },\n    \"project\": {\n      \"description\": \"The key of the project that will own the webhook\",\n      \"maxLength\": 400,\n      \"type\": \"string\"\n    },\n    \"secret\": {\n      \"description\": \"If provided, secret will be used as the key to generate the HMAC hex (lowercase) digest value in the 'X-Sonar-Webhook-HMAC-SHA256' header\",\n      \"maxLength\": 200,\n      \"minLength\": 16,\n      \"type\": \"string\"\n    },\n    \"url\": {\n      \"description\": \"Server endpoint that will receive the webhook payload, for example 'http://my_server/foo'. If HTTP Basic authentication is used, HTTPS is recommended to avoid man in the middle attacks. Example: 'https://myLogin:myPassword@my_server/foo'\",\n      \"maxLength\": 512,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\",\n    \"url\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the PostWebhooksCreate tool (Status: 200, Content-Type: application/json)
const PostWebhooksCreateResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewPostWebhooksCreateMCPTool creates the MCP Tool instance for PostWebhooksCreate
func NewPostWebhooksCreateMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostWebhooksCreate",
		"Create a Webhook. - Create a Webhook. Requires 'Administer' permission on the specified project, or global 'Administer' permission.",
		[]byte(PostWebhooksCreateInputSchema),
	)
}

// PostWebhooksCreateHandler is the handler function for the PostWebhooksCreate tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostWebhooksCreateHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	startTime := time.Now()
	resp, err := mcputils.ForwardRequest(ctx, upstream, "POST", "/api/webhooks/create", args, []string{}, contentType)
	if err != nil {
		return nil, fmt.Errorf("upstream request failed: %w", err)
	}
	defer resp.Body.Close()

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), nil)

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return mcp.NewToolResultError(fmt.Sprintf("upstream error: status %d, body: %s", resp.StatusCode, string(body))), nil
	}

	if mcputils.IsBinaryDownload(resp) {
		filePath, written, err := mcputils.SaveBinaryStream(resp, "PostWebhooksCreate")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		return mcp.NewToolResultText(fmt.Sprintf("Saved to: %s (%d bytes)", filePath, written)), nil
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read upstream response: %w", err)
	}

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), body)

	return mcp.NewToolResultText(string(body)), nil
}
