// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"fmt"
	"github.com/mark3labs/mcp-go/mcp"
	"io"
	"sonarqube-mcp/pkg/helpers"
	"time"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostProjectTagsSet tool
const PostProjectTagsSetInputSchema = "{\n  \"properties\": {\n    \"project\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    },\n    \"tags\": {\n      \"description\": \"Comma-separated list of tags\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"project\",\n    \"tags\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostProjectTagsSetMCPTool creates the MCP Tool instance for PostProjectTagsSet
func NewPostProjectTagsSetMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostProjectTagsSet",
		"Set tags on a project. - Set tags on a project. Requires the following permission: 'Administer' rights on the specified project",
		[]byte(PostProjectTagsSetInputSchema),
	)
}

// PostProjectTagsSetHandler is the handler function for the PostProjectTagsSet tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostProjectTagsSetHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	startTime := time.Now()
	resp, err := mcputils.ForwardRequest(ctx, upstream, "POST", "/api/project_tags/set", args, []string{}, contentType)
	if err != nil {
		return nil, fmt.Errorf("upstream request failed: %w", err)
	}
	defer resp.Body.Close()

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), nil)

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return mcp.NewToolResultError(fmt.Sprintf("upstream error: status %d, body: %s", resp.StatusCode, string(body))), nil
	}

	if mcputils.IsBinaryDownload(resp) {
		filePath, written, err := mcputils.SaveBinaryStream(resp, "PostProjectTagsSet")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		return mcp.NewToolResultText(fmt.Sprintf("Saved to: %s (%d bytes)", filePath, written)), nil
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read upstream response: %w", err)
	}

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), body)

	return mcp.NewToolResultText(string(body)), nil
}
