// Code generated by https://github.com/wl4g-ai/mcpgen-go

package mcptools

import (
	"context"
	"fmt"
	"github.com/mark3labs/mcp-go/mcp"
	"io"
	"sonarqube-mcp/pkg/helpers"
	"time"
)

// Code generated by https://github.com/wl4g-ai/mcpgen-go

// Input Schema for the PostAlmSettingsCreateGithub tool
const PostAlmSettingsCreateGithubInputSchema = "{\n  \"properties\": {\n    \"appId\": {\n      \"description\": \"GitHub App ID\",\n      \"maxLength\": 80,\n      \"type\": \"string\"\n    },\n    \"clientId\": {\n      \"description\": \"GitHub App Client ID\",\n      \"maxLength\": 80,\n      \"type\": \"string\"\n    },\n    \"clientSecret\": {\n      \"description\": \"GitHub App Client Secret\",\n      \"maxLength\": 160,\n      \"type\": \"string\"\n    },\n    \"key\": {\n      \"description\": \"Unique key of the GitHub instance setting\",\n      \"maxLength\": 200,\n      \"type\": \"string\"\n    },\n    \"privateKey\": {\n      \"description\": \"GitHub App private key\",\n      \"maxLength\": 2500,\n      \"type\": \"string\"\n    },\n    \"url\": {\n      \"description\": \"GitHub API URL\",\n      \"maxLength\": 2000,\n      \"type\": \"string\"\n    },\n    \"webhookSecret\": {\n      \"description\": \"GitHub App Webhook Secret\",\n      \"maxLength\": 160,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"appId\",\n    \"clientId\",\n    \"clientSecret\",\n    \"key\",\n    \"privateKey\",\n    \"url\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostAlmSettingsCreateGithubMCPTool creates the MCP Tool instance for PostAlmSettingsCreateGithub
func NewPostAlmSettingsCreateGithubMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostAlmSettingsCreateGithub",
		"Create GitHub instance Setting. - Create GitHub instance Setting. Requires the 'Administer System' permission",
		[]byte(PostAlmSettingsCreateGithubInputSchema),
	)
}

// PostAlmSettingsCreateGithubHandler is the handler function for the PostAlmSettingsCreateGithub tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostAlmSettingsCreateGithubHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	startTime := time.Now()
	resp, err := mcputils.ForwardRequest(ctx, upstream, "POST", "/api/alm_settings/create_github", args, []string{}, contentType)
	if err != nil {
		return nil, fmt.Errorf("upstream request failed: %w", err)
	}
	defer resp.Body.Close()

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), nil)

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return mcp.NewToolResultError(fmt.Sprintf("upstream error: status %d, body: %s", resp.StatusCode, string(body))), nil
	}

	if mcputils.IsBinaryDownload(resp) {
		filePath, written, err := mcputils.SaveBinaryStream(resp, "PostAlmSettingsCreateGithub")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		return mcp.NewToolResultText(fmt.Sprintf("Saved to: %s (%d bytes)", filePath, written)), nil
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read upstream response: %w", err)
	}

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), body)

	return mcp.NewToolResultText(string(body)), nil
}
