// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"fmt"
	"github.com/mark3labs/mcp-go/mcp"
	"io"
	"sonarqube-mcp/pkg/helpers"
	"time"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostFavoritesRemove tool
const PostFavoritesRemoveInputSchema = "{\n  \"properties\": {\n    \"component\": {\n      \"description\": \"Component key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"component\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostFavoritesRemoveMCPTool creates the MCP Tool instance for PostFavoritesRemove
func NewPostFavoritesRemoveMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostFavoritesRemove",
		"Remove a component (project, portfolio, application etc.) as favorite for the authenticated user. - Remove a component (project, portfolio, application etc.) as favorite for the authenticated user. Requires authentication.",
		[]byte(PostFavoritesRemoveInputSchema),
	)
}

// PostFavoritesRemoveHandler is the handler function for the PostFavoritesRemove tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostFavoritesRemoveHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	startTime := time.Now()
	resp, err := mcputils.ForwardRequest(ctx, upstream, "POST", "/api/favorites/remove", args, []string{}, contentType)
	if err != nil {
		return nil, fmt.Errorf("upstream request failed: %w", err)
	}
	defer resp.Body.Close()

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), nil)

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return mcp.NewToolResultError(fmt.Sprintf("upstream error: status %d, body: %s", resp.StatusCode, string(body))), nil
	}

	if mcputils.IsBinaryDownload(resp) {
		filePath, written, err := mcputils.SaveBinaryStream(resp, "PostFavoritesRemove")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		return mcp.NewToolResultText(fmt.Sprintf("Saved to: %s (%d bytes)", filePath, written)), nil
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read upstream response: %w", err)
	}

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), body)

	return mcp.NewToolResultText(string(body)), nil
}
