// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"fmt"
	"github.com/mark3labs/mcp-go/mcp"
	"io"
	"sonarqube-mcp/pkg/helpers"
	"time"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostViewsRemoveProjectBranch tool
const PostViewsRemoveProjectBranchInputSchema = "{\n  \"properties\": {\n    \"branch\": {\n      \"description\": \"Key of the branch\",\n      \"type\": \"string\"\n    },\n    \"key\": {\n      \"description\": \"Key of the portfolio\",\n      \"type\": \"string\"\n    },\n    \"project\": {\n      \"description\": \"Key of the project\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"branch\",\n    \"key\",\n    \"project\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostViewsRemoveProjectBranchMCPTool creates the MCP Tool instance for PostViewsRemoveProjectBranch
func NewPostViewsRemoveProjectBranchMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostViewsRemoveProjectBranch",
		"Remove a branch of a project selected in a portfolio. - Remove a branch of a project selected in a portfolio. Requires 'Administrator' permission on the portfolio and 'Browse' permission for the project.",
		[]byte(PostViewsRemoveProjectBranchInputSchema),
	)
}

// PostViewsRemoveProjectBranchHandler is the handler function for the PostViewsRemoveProjectBranch tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostViewsRemoveProjectBranchHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	startTime := time.Now()
	resp, err := mcputils.ForwardRequest(ctx, upstream, "POST", "/api/views/remove_project_branch", args, []string{}, contentType)
	if err != nil {
		return nil, fmt.Errorf("upstream request failed: %w", err)
	}
	defer resp.Body.Close()

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), nil)

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return mcp.NewToolResultError(fmt.Sprintf("upstream error: status %d, body: %s", resp.StatusCode, string(body))), nil
	}

	if mcputils.IsBinaryDownload(resp) {
		filePath, written, err := mcputils.SaveBinaryStream(resp, "PostViewsRemoveProjectBranch")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		return mcp.NewToolResultText(fmt.Sprintf("Saved to: %s (%d bytes)", filePath, written)), nil
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read upstream response: %w", err)
	}

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), body)

	return mcp.NewToolResultText(string(body)), nil
}
