// Code generated by https://github.com/wl4g-ai/mcpgen-go

package mcptools

import (
	"context"
	"fmt"
	"github.com/mark3labs/mcp-go/mcp"
	"io"
	"sonarqube-mcp/pkg/helpers"
	"time"
)

// Code generated by https://github.com/wl4g-ai/mcpgen-go

// Input Schema for the PostQualityprofilesDeactivateRule tool
const PostQualityprofilesDeactivateRuleInputSchema = "{\n  \"properties\": {\n    \"key\": {\n      \"description\": \"Quality Profile key. Can be obtained through api/qualityprofiles/search\",\n      \"type\": \"string\"\n    },\n    \"rule\": {\n      \"description\": \"Rule key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"key\",\n    \"rule\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostQualityprofilesDeactivateRuleMCPTool creates the MCP Tool instance for PostQualityprofilesDeactivateRule
func NewPostQualityprofilesDeactivateRuleMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostQualityprofilesDeactivateRule",
		"Deactivate a rule on a quality profile. - Deactivate a rule on a quality profile. Requires one of the following permissions: - 'Administer Quality Profiles' - Edit right on the specified quality profile",
		[]byte(PostQualityprofilesDeactivateRuleInputSchema),
	)
}

// PostQualityprofilesDeactivateRuleHandler is the handler function for the PostQualityprofilesDeactivateRule tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostQualityprofilesDeactivateRuleHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	startTime := time.Now()
	resp, err := mcputils.ForwardRequest(ctx, upstream, "POST", "/api/qualityprofiles/deactivate_rule", args, []string{}, contentType)
	if err != nil {
		return nil, fmt.Errorf("upstream request failed: %w", err)
	}
	defer resp.Body.Close()

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), nil)

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return mcp.NewToolResultError(fmt.Sprintf("upstream error: status %d, body: %s", resp.StatusCode, string(body))), nil
	}

	if mcputils.IsBinaryDownload(resp) {
		filePath, written, err := mcputils.SaveBinaryStream(resp, "PostQualityprofilesDeactivateRule")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		return mcp.NewToolResultText(fmt.Sprintf("Saved to: %s (%d bytes)", filePath, written)), nil
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read upstream response: %w", err)
	}

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), body)

	return mcp.NewToolResultText(string(body)), nil
}
