// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"fmt"
	"github.com/mark3labs/mcp-go/mcp"
	"io"
	"sonarqube-mcp/pkg/helpers"
	"time"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostProjectsUpdateKey tool
const PostProjectsUpdateKeyInputSchema = "{\n  \"properties\": {\n    \"from\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    },\n    \"to\": {\n      \"description\": \"New project key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"from\",\n    \"to\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostProjectsUpdateKeyMCPTool creates the MCP Tool instance for PostProjectsUpdateKey
func NewPostProjectsUpdateKeyMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostProjectsUpdateKey",
		"Update a project all its sub-components keys. - Update a project all its sub-components keys. Requires 'Administer' permission on the project.",
		[]byte(PostProjectsUpdateKeyInputSchema),
	)
}

// PostProjectsUpdateKeyHandler is the handler function for the PostProjectsUpdateKey tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostProjectsUpdateKeyHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	startTime := time.Now()
	resp, err := mcputils.ForwardRequest(ctx, upstream, "POST", "/api/projects/update_key", args, []string{}, contentType)
	if err != nil {
		return nil, fmt.Errorf("upstream request failed: %w", err)
	}
	defer resp.Body.Close()

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), nil)

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return mcp.NewToolResultError(fmt.Sprintf("upstream error: status %d, body: %s", resp.StatusCode, string(body))), nil
	}

	if mcputils.IsBinaryDownload(resp) {
		filePath, written, err := mcputils.SaveBinaryStream(resp, "PostProjectsUpdateKey")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		return mcp.NewToolResultText(fmt.Sprintf("Saved to: %s (%d bytes)", filePath, written)), nil
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read upstream response: %w", err)
	}

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), body)

	return mcp.NewToolResultText(string(body)), nil
}
