// Code generated by https://github.com/wl4g-ai/mcpgen-go

package mcptools

import (
	"context"
	"fmt"
	"github.com/mark3labs/mcp-go/mcp"
	"io"
	"sonarqube-mcp/pkg/helpers"
	"time"
)

// Code generated by https://github.com/wl4g-ai/mcpgen-go

// Input Schema for the PostGovernanceReportsSubscribe tool
const PostGovernanceReportsSubscribeInputSchema = "{\n  \"properties\": {\n    \"branchKey\": {\n      \"description\": \"The branch key\",\n      \"type\": \"string\"\n    },\n    \"componentId\": {\n      \"description\": \"The portfolio, sub-portfolio, project or application id\",\n      \"type\": \"string\"\n    },\n    \"componentKey\": {\n      \"description\": \"The portfolio, sub-portfolio, project or application key\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewPostGovernanceReportsSubscribeMCPTool creates the MCP Tool instance for PostGovernanceReportsSubscribe
func NewPostGovernanceReportsSubscribeMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostGovernanceReportsSubscribe",
		"Subscribe the current user to reports for a portfolio, a sub-portfolio, a project or an application. - Subscribe the current user to reports for a portfolio, a sub-portfolio, a project or an application. Fails when the user has no email address configured. Requires authentication and the 'Browse' permission on the portfolio, a sub-portfolio, project or application. For applications, it also requires 'Browse' permission on its child projects.",
		[]byte(PostGovernanceReportsSubscribeInputSchema),
	)
}

// PostGovernanceReportsSubscribeHandler is the handler function for the PostGovernanceReportsSubscribe tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostGovernanceReportsSubscribeHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	startTime := time.Now()
	resp, err := mcputils.ForwardRequest(ctx, upstream, "POST", "/api/governance_reports/subscribe", args, []string{}, contentType)
	if err != nil {
		return nil, fmt.Errorf("upstream request failed: %w", err)
	}
	defer resp.Body.Close()

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), nil)

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return mcp.NewToolResultError(fmt.Sprintf("upstream error: status %d, body: %s", resp.StatusCode, string(body))), nil
	}

	if mcputils.IsBinaryDownload(resp) {
		filePath, written, err := mcputils.SaveBinaryStream(resp, "PostGovernanceReportsSubscribe")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		return mcp.NewToolResultText(fmt.Sprintf("Saved to: %s (%d bytes)", filePath, written)), nil
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read upstream response: %w", err)
	}

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), body)

	return mcp.NewToolResultText(string(body)), nil
}
