// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"fmt"
	"github.com/mark3labs/mcp-go/mcp"
	"io"
	"sonarqube-mcp/pkg/helpers"
	"time"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostQualityprofilesCopy tool
const PostQualityprofilesCopyInputSchema = "{\n  \"properties\": {\n    \"fromKey\": {\n      \"description\": \"Quality profile key\",\n      \"type\": \"string\"\n    },\n    \"toName\": {\n      \"description\": \"Name for the new quality profile.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"fromKey\",\n    \"toName\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the PostQualityprofilesCopy tool (Status: 200, Content-Type: application/json)
const PostQualityprofilesCopyResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewPostQualityprofilesCopyMCPTool creates the MCP Tool instance for PostQualityprofilesCopy
func NewPostQualityprofilesCopyMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostQualityprofilesCopy",
		"Copy a quality profile. - Copy a quality profile. Requires to be logged in and the 'Administer Quality Profiles' permission.",
		[]byte(PostQualityprofilesCopyInputSchema),
	)
}

// PostQualityprofilesCopyHandler is the handler function for the PostQualityprofilesCopy tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostQualityprofilesCopyHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	startTime := time.Now()
	resp, err := mcputils.ForwardRequest(ctx, upstream, "POST", "/api/qualityprofiles/copy", args, []string{}, contentType)
	if err != nil {
		return nil, fmt.Errorf("upstream request failed: %w", err)
	}
	defer resp.Body.Close()

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), nil)

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return mcp.NewToolResultError(fmt.Sprintf("upstream error: status %d, body: %s", resp.StatusCode, string(body))), nil
	}

	if mcputils.IsBinaryDownload(resp) {
		filePath, written, err := mcputils.SaveBinaryStream(resp, "PostQualityprofilesCopy")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		return mcp.NewToolResultText(fmt.Sprintf("Saved to: %s (%d bytes)", filePath, written)), nil
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read upstream response: %w", err)
	}

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), body)

	return mcp.NewToolResultText(string(body)), nil
}
