// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"fmt"
	"github.com/mark3labs/mcp-go/mcp"
	"io"
	"sonarqube-mcp/pkg/helpers"
	"time"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostQualitygatesRemoveGroup tool
const PostQualitygatesRemoveGroupInputSchema = "{\n  \"properties\": {\n    \"gateName\": {\n      \"description\": \"Quality Gate name\",\n      \"maxLength\": 100,\n      \"type\": \"string\"\n    },\n    \"groupName\": {\n      \"description\": \"Group name or 'anyone' (case insensitive)\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"gateName\",\n    \"groupName\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostQualitygatesRemoveGroupMCPTool creates the MCP Tool instance for PostQualitygatesRemoveGroup
func NewPostQualitygatesRemoveGroupMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostQualitygatesRemoveGroup",
		"Remove the ability from a group to edit a Quality Gate. - Remove the ability from a group to edit a Quality Gate. Requires one of the following permissions: - 'Administer Quality Gates' - Edit right on the specified quality gate",
		[]byte(PostQualitygatesRemoveGroupInputSchema),
	)
}

// PostQualitygatesRemoveGroupHandler is the handler function for the PostQualitygatesRemoveGroup tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostQualitygatesRemoveGroupHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	startTime := time.Now()
	resp, err := mcputils.ForwardRequest(ctx, upstream, "POST", "/api/qualitygates/remove_group", args, []string{}, contentType)
	if err != nil {
		return nil, fmt.Errorf("upstream request failed: %w", err)
	}
	defer resp.Body.Close()

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), nil)

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return mcp.NewToolResultError(fmt.Sprintf("upstream error: status %d, body: %s", resp.StatusCode, string(body))), nil
	}

	if mcputils.IsBinaryDownload(resp) {
		filePath, written, err := mcputils.SaveBinaryStream(resp, "PostQualitygatesRemoveGroup")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		return mcp.NewToolResultText(fmt.Sprintf("Saved to: %s (%d bytes)", filePath, written)), nil
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read upstream response: %w", err)
	}

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), body)

	return mcp.NewToolResultText(string(body)), nil
}
