// Code generated by https://github.com/wl4g-ai/mcpgen-go

package mcptools

import (
	"context"
	"fmt"
	"github.com/mark3labs/mcp-go/mcp"
	"io"
	"sonarqube-mcp/pkg/helpers"
	"time"
)

// Code generated by https://github.com/wl4g-ai/mcpgen-go

// Input Schema for the PostProjectAnalysesCreateEvent tool
const PostProjectAnalysesCreateEventInputSchema = "{\n  \"properties\": {\n    \"analysis\": {\n      \"description\": \"Analysis key\",\n      \"type\": \"string\"\n    },\n    \"category\": {\n      \"description\": \"Category\",\n      \"enum\": [\n        \"VERSION\",\n        \"OTHER\"\n      ],\n      \"type\": \"string\"\n    },\n    \"name\": {\n      \"description\": \"Name\",\n      \"maxLength\": 400,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"analysis\",\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the PostProjectAnalysesCreateEvent tool (Status: 200, Content-Type: application/json)
const PostProjectAnalysesCreateEventResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewPostProjectAnalysesCreateEventMCPTool creates the MCP Tool instance for PostProjectAnalysesCreateEvent
func NewPostProjectAnalysesCreateEventMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostProjectAnalysesCreateEvent",
		"Create a project analysis event. - Create a project analysis event. Only event of category 'VERSION' and 'OTHER' can be created. Requires one of the following permissions: - 'Administer System' - 'Administer' rights on the specified project",
		[]byte(PostProjectAnalysesCreateEventInputSchema),
	)
}

// PostProjectAnalysesCreateEventHandler is the handler function for the PostProjectAnalysesCreateEvent tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostProjectAnalysesCreateEventHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	startTime := time.Now()
	resp, err := mcputils.ForwardRequest(ctx, upstream, "POST", "/api/project_analyses/create_event", args, []string{}, contentType)
	if err != nil {
		return nil, fmt.Errorf("upstream request failed: %w", err)
	}
	defer resp.Body.Close()

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), nil)

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return mcp.NewToolResultError(fmt.Sprintf("upstream error: status %d, body: %s", resp.StatusCode, string(body))), nil
	}

	if mcputils.IsBinaryDownload(resp) {
		filePath, written, err := mcputils.SaveBinaryStream(resp, "PostProjectAnalysesCreateEvent")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		return mcp.NewToolResultText(fmt.Sprintf("Saved to: %s (%d bytes)", filePath, written)), nil
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read upstream response: %w", err)
	}

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), body)

	return mcp.NewToolResultText(string(body)), nil
}
