// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"fmt"
	"github.com/mark3labs/mcp-go/mcp"
	"io"
	"sonarqube-mcp/pkg/helpers"
	"time"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostViewsSetNoneMode tool
const PostViewsSetNoneModeInputSchema = "{\n  \"properties\": {\n    \"portfolio\": {\n      \"description\": \"Key of the portfolio or sub-portfolio to update\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"portfolio\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostViewsSetNoneModeMCPTool creates the MCP Tool instance for PostViewsSetNoneMode
func NewPostViewsSetNoneModeMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostViewsSetNoneMode",
		"Set the projects selection mode of a portfolio to none. - Set the projects selection mode of a portfolio to none. After setting this mode portfolio will not have any projects assigned. Requires 'Administrator' permission on the portfolio.",
		[]byte(PostViewsSetNoneModeInputSchema),
	)
}

// PostViewsSetNoneModeHandler is the handler function for the PostViewsSetNoneMode tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostViewsSetNoneModeHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	startTime := time.Now()
	resp, err := mcputils.ForwardRequest(ctx, upstream, "POST", "/api/views/set_none_mode", args, []string{}, contentType)
	if err != nil {
		return nil, fmt.Errorf("upstream request failed: %w", err)
	}
	defer resp.Body.Close()

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), nil)

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return mcp.NewToolResultError(fmt.Sprintf("upstream error: status %d, body: %s", resp.StatusCode, string(body))), nil
	}

	if mcputils.IsBinaryDownload(resp) {
		filePath, written, err := mcputils.SaveBinaryStream(resp, "PostViewsSetNoneMode")
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		return mcp.NewToolResultText(fmt.Sprintf("Saved to: %s (%d bytes)", filePath, written)), nil
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read upstream response: %w", err)
	}

	mcputils.LogResponse(ctx, resp.StatusCode, "POST", resp.Request.URL.String(), time.Since(startTime), body)

	return mcp.NewToolResultText(string(body)), nil
}
