package generator

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
)

const (
	maxSearchDepth = 50
	goModFile      = "go.mod"
	minGoMajor     = 1
	minGoMinor     = 24
)

// BuildModuleName computes the module name from the output directory basename.
// e.g. outputDir "mymcpserver" → "mymcpserver"
func BuildModuleName(outputDir string) string {
	base := filepath.Base(filepath.Clean(outputDir))
	return base
}

// BuildImportPath returns the import path for the mcptools package within the
// generated standalone project (e.g. "mymcpserver/pkg/mcptools").
func BuildImportPath(outputDir string) (string, error) {
	moduleName := BuildModuleName(outputDir)
	return moduleName + "/pkg/mcptools", nil
}

// BuildServerImportPath returns the import path for the mcpserver package.
func BuildServerImportPath(outputDir string) (string, error) {
	moduleName := BuildModuleName(outputDir)
	return moduleName + "/pkg/mcpserver", nil
}

// GenerateGoMod creates a go.mod file in the output directory for the standalone project.
// It uses the current Go version detected from the runtime.
func GenerateGoMod(outputDir string) error {
	moduleName := BuildModuleName(outputDir)
	goVersion := runtime.Version()
	// runtime.Version() returns e.g. "go1.23.4" or "go1.23.4-final"
	goVersion = strings.TrimPrefix(goVersion, "go")
	if idx := strings.IndexByte(goVersion, '-'); idx != -1 {
		goVersion = goVersion[:idx]
	}
	// Keep only major.minor (e.g. "1.23")
	if parts := strings.Split(goVersion, "."); len(parts) >= 2 {
		goVersion = strings.Join(parts[:2], ".")
		// Cap at minimum supported version — generated code doesn't need newer Go.
		if major, err := strconv.Atoi(parts[0]); err == nil {
			if minor, err := strconv.Atoi(parts[1]); err == nil {
				if major > minGoMajor || (major == minGoMajor && minor > minGoMinor) {
					goVersion = fmt.Sprintf("%d.%d", minGoMajor, minGoMinor)
				}
			}
		}
	}

	content := fmt.Sprintf("// Generated by https://github.com/flowgent-labs/mcpfather\n\nmodule %s\n\ngo %s\n\nrequire (\n\tgithub.com/MicahParks/keyfunc/v3 v3.8.0\n\tgithub.com/go-ldap/ldap/v3 v3.4.13\n\tgithub.com/golang-jwt/jwt/v5 v5.3.1\n\tgithub.com/itchyny/gojq v0.12.19\n\tgithub.com/mark3labs/mcp-go v0.55.1\n\tgithub.com/go-viper/mapstructure/v2 v2.2.1\n\tgithub.com/prometheus/client_golang v1.20.5\n\tgithub.com/spf13/viper v1.20.1\n\tgo.opentelemetry.io/otel v1.28.0\n\tgo.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.28.0\n\tgo.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp v1.28.0\n\tgo.opentelemetry.io/otel/exporters/prometheus v0.50.0\n\tgo.opentelemetry.io/otel/sdk v1.28.0\n\tgo.opentelemetry.io/otel/sdk/metric v1.28.0\n\tgopkg.in/yaml.v3 v3.0.1\n)\n", moduleName, goVersion)

	goModPath := filepath.Join(outputDir, "go.mod")
	return os.WriteFile(goModPath, []byte(content), 0644)
}

// findModulePath searches upward from startDir to find the go.mod file
func findModulePath(startDir string) (string, string, error) {
	currentDir := filepath.Clean(startDir)
	for depth := 0; depth < maxSearchDepth; depth++ {
		goModPath := filepath.Join(currentDir, goModFile)

		// Check if go.mod exists
		if _, err := os.Stat(goModPath); err == nil {
			moduleName, err := parseModuleName(goModPath)
			if err != nil {
				return "", "", err
			}
			return moduleName, currentDir, nil
		} else if !os.IsNotExist(err) {
			return "", "", fmt.Errorf("error checking for go.mod: %w", err)
		}

		// Move up one directory
		parent := filepath.Dir(currentDir)
		if parent == currentDir {
			break // Reached filesystem root
		}
		currentDir = parent
	}

	return "", "", fmt.Errorf("no go.mod found in %d levels from %s",
		maxSearchDepth, startDir)
}

// parseModuleName extracts the module name from go.mod file
func parseModuleName(goModPath string) (string, error) {
	file, err := os.Open(goModPath)
	if err != nil {
		return "", fmt.Errorf("failed to open %s: %w", goModPath, err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "module") {
			modulePart := strings.TrimSpace(strings.TrimPrefix(line, "module"))
			if i := strings.Index(modulePart, "//"); i != -1 {
				modulePart = strings.TrimSpace(modulePart[:i])
			}

			if len(modulePart) > 0 && (modulePart[0] == '"' || modulePart[0] == '\'') {
				quote := modulePart[0]
				end := strings.IndexByte(modulePart[1:], quote)
				if end == -1 {
					return "", fmt.Errorf("unclosed quote in module declaration in %s: %s", goModPath, line)
				}
				return modulePart[1 : end+1], nil
			}

			fields := strings.Fields(modulePart)
			if len(fields) == 0 {
				return "", fmt.Errorf("empty module name after 'module' keyword in %s: %s", goModPath, line)
			}
			return fields[0], nil
		}
	}

	if err := scanner.Err(); err != nil {
		return "", fmt.Errorf("error scanning go.mod: %w", err)
	}

	return "", fmt.Errorf("module declaration not found in %s", goModPath)
}
