package generator

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// virtualSrcPrefix is the import path used in the embedded virtual engine source files.
const virtualSrcPrefix = "github.com/wl4g-ai/mcpgen/pkg/generator/mcpvirtual"

// GenerateVirtual copies the virtual tool engine source files into the
// generated project as pkg/mcpvirtual/, rewriting import paths.
func (g *Generator) GenerateVirtual() error {
	destDir := filepath.Join(g.outputDir, "pkg", "mcpvirtual")
	moduleName := BuildModuleName(g.outputDir)
	destImportPrefix := moduleName + "/pkg/mcpvirtual"

	return fs.WalkDir(templatesFS, "mcpvirtual", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		if !strings.HasSuffix(path, ".go") {
			return nil
		}

		content, err := templatesFS.ReadFile(path)
		if err != nil {
			return fmt.Errorf("failed to read embedded %s: %w", path, err)
		}

		// Rewrite import paths
		src := "// Code generated by https://github.com/wl4g-ai/mcpgen-go\n\n" + strings.ReplaceAll(string(content), virtualSrcPrefix, destImportPrefix)

		// Compute destination path: strip "mcpvirtual/" prefix
		relPath := strings.TrimPrefix(path, "mcpvirtual/")
		destPath := filepath.Join(destDir, relPath)

		if err := os.MkdirAll(filepath.Dir(destPath), 0755); err != nil {
			return fmt.Errorf("failed to create dir %s: %w", filepath.Dir(destPath), err)
		}
		if err := os.WriteFile(destPath, []byte(src), 0644); err != nil {
			return fmt.Errorf("failed to write %s: %w", destPath, err)
		}
		return nil
	})
}
