// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the AcknowledgeErrors tool
const AcknowledgeErrorsInputSchema = "{\n  \"type\": \"object\"\n}"

// NewAcknowledgeErrorsMCPTool creates the MCP Tool instance for AcknowledgeErrors
func NewAcknowledgeErrorsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"AcknowledgeErrors",
		"Retry cluster upgrade - Retries the cluster upgrade.",
		[]byte(AcknowledgeErrorsInputSchema),
	)
}

// AcknowledgeErrorsHandler is the handler function for the AcknowledgeErrors tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func AcknowledgeErrorsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/rest/api/2/cluster/zdu/retryUpgrade", args, []string{}, contentType, "AcknowledgeErrors")
}
