// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the AddVote tool
const AddVoteInputSchema = "{\n  \"properties\": {\n    \"issueIdOrKey\": {\n      \"description\": \"Issue id.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"issueIdOrKey\"\n  ],\n  \"type\": \"object\"\n}"

// NewAddVoteMCPTool creates the MCP Tool instance for AddVote
func NewAddVoteMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"AddVote",
		"Add vote to issue - Adds voter (currently logged user) to particular ticket. You need to be logged in to use this method.",
		[]byte(AddVoteInputSchema),
	)
}

// AddVoteHandler is the handler function for the AddVote tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func AddVoteHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/rest/api/2/issue/{issueIdOrKey}/votes", args, []string{"issueIdOrKey"}, contentType, "AddVote")
}
