// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the BulkDeleteCustomFields tool
const BulkDeleteCustomFieldsInputSchema = "{\n  \"properties\": {\n    \"ids\": {\n      \"description\": \"A list of custom field IDs to delete.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"ids\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the BulkDeleteCustomFields tool (Status: 200, Content-Type: application/json)
const BulkDeleteCustomFieldsResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Returned if at least one custom field was deleted\n\n## Response Structure\n\n- Structure (Type: object):\n  - **deletedCustomFields** (Type: array):\n      - Example: '[\"customfield_10000\"]'\n    - **Items** (Type: string):\n        - Example: '[\"customfield_10000\"]'\n  - **message** (Type: string):\n      - Example: 'Custom fields bulk delete operation finished.'\n  - **notDeletedCustomFields** (Type: object):\n      - Example: '{\"customfield_10001\":\"Validation for custom field deletion failed.\"}'\n    - **Additional Properties**:\n      - **property value** (Type: string):\n          - Example: '{\"customfield_10001\":\"Validation for custom field deletion failed.\"}'\n"

// NewBulkDeleteCustomFieldsMCPTool creates the MCP Tool instance for BulkDeleteCustomFields
func NewBulkDeleteCustomFieldsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"BulkDeleteCustomFields",
		"Delete custom fields in bulk - Deletes custom fields in bulk.",
		[]byte(BulkDeleteCustomFieldsInputSchema),
	)
}

// BulkDeleteCustomFieldsHandler is the handler function for the BulkDeleteCustomFields tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func BulkDeleteCustomFieldsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/rest/api/2/customFields", args, []string{}, contentType, "BulkDeleteCustomFields")
}
