// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CancelUpgrade tool
const CancelUpgradeInputSchema = "{\n  \"type\": \"object\"\n}"

// NewCancelUpgradeMCPTool creates the MCP Tool instance for CancelUpgrade
func NewCancelUpgradeMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CancelUpgrade",
		"Cancel cluster upgrade - Cancels the ongoing cluster upgrade.",
		[]byte(CancelUpgradeInputSchema),
	)
}

// CancelUpgradeHandler is the handler function for the CancelUpgrade tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CancelUpgradeHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/rest/api/2/cluster/zdu/cancel", args, []string{}, contentType, "CancelUpgrade")
}
