// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateUser tool
const CreateUserInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"description\": \"User details\",\n      \"properties\": {\n        \"active\": {\n          \"example\": true,\n          \"type\": \"boolean\"\n        },\n        \"applicationKeys\": {\n          \"example\": [\n            \"jira-core\"\n          ],\n          \"items\": {\n            \"example\": \"[\\\"jira-core\\\"]\",\n            \"type\": \"string\"\n          },\n          \"type\": \"array\"\n        },\n        \"displayName\": {\n          \"example\": \"Charlie of Atlassian\",\n          \"type\": \"string\"\n        },\n        \"emailAddress\": {\n          \"example\": \"charlie@atlassian.com\",\n          \"type\": \"string\"\n        },\n        \"key\": {\n          \"example\": \"charlie\",\n          \"type\": \"string\"\n        },\n        \"name\": {\n          \"example\": \"charlie\",\n          \"type\": \"string\"\n        },\n        \"notification\": {\n          \"example\": \"HTML\",\n          \"type\": \"string\"\n        },\n        \"password\": {\n          \"example\": \"abracadabra\",\n          \"type\": \"string\"\n        },\n        \"self\": {\n          \"example\": \"http://www.example.com/jira/rest/api/2/user?username=charlie\",\n          \"type\": \"string\"\n        }\n      },\n      \"type\": \"object\"\n    }\n  },\n  \"required\": [\n    \"body\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the CreateUser tool (Status: 201, Content-Type: application/json)
const CreateUserResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 201\n\n**Content-Type:** application/json\n\n> Returned if the user was created.\n\n## Response Structure\n\n- Structure (Type: object):\n  - **active** (Type: boolean):\n      - Example: 'true'\n  - **applicationKeys** (Type: array):\n      - Example: '[\"jira-core\"]'\n    - **Items** (Type: string):\n        - Example: '[\"jira-core\"]'\n  - **displayName** (Type: string):\n      - Example: 'Charlie of Atlassian'\n  - **emailAddress** (Type: string):\n      - Example: 'charlie@atlassian.com'\n  - **key** (Type: string):\n      - Example: 'charlie'\n  - **name** (Type: string):\n      - Example: 'charlie'\n  - **notification** (Type: string):\n      - Example: 'HTML'\n  - **password** (Type: string):\n      - Example: 'abracadabra'\n  - **self** (Type: string):\n      - Example: 'http://www.example.com/jira/rest/api/2/user?username=charlie'\n"

// NewCreateUserMCPTool creates the MCP Tool instance for CreateUser
func NewCreateUserMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateUser",
		"Create new user - Create user. By default created user will not be notified with email. If password field is not set then password will be randomly generated.",
		[]byte(CreateUserInputSchema),
	)
}

// CreateUserHandler is the handler function for the CreateUser tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateUserHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/rest/api/2/user", args, []string{}, contentType, "CreateUser")
}
