// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DefaultColumns tool
const DefaultColumnsInputSchema = "{\n  \"properties\": {\n    \"username\": {\n      \"description\": \"username\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the DefaultColumns tool (Status: 200, Content-Type: application/json)
const DefaultColumnsResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Returns a list of columns for configured for the given user\n\n## Response Structure\n\n- Structure (Type: object):\n"

// NewDefaultColumnsMCPTool creates the MCP Tool instance for DefaultColumns
func NewDefaultColumnsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DefaultColumns",
		"Get default columns for user - Returns the default columns for the given user. Admin permission will be required to get columns for a user other than the currently logged in user.",
		[]byte(DefaultColumnsInputSchema),
	)
}

// DefaultColumnsHandler is the handler function for the DefaultColumns tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DefaultColumnsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/rest/api/2/user/columns", args, []string{}, contentType, "DefaultColumns")
}
