// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteIssueType1 tool
const DeleteIssueType1InputSchema = "{\n  \"properties\": {\n    \"alternativeIssueTypeId\": {\n      \"description\": \"The id of an issue type to which issues associated with the removed issue type will be migrated.\",\n      \"type\": \"string\"\n    },\n    \"id\": {\n      \"description\": \"The issue type id.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"alternativeIssueTypeId\",\n    \"id\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteIssueType1MCPTool creates the MCP Tool instance for DeleteIssueType1
func NewDeleteIssueType1MCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteIssueType1",
		"Delete specified issue type and migrate associated issues - Deletes the specified issue type. If the issue type has any associated issues, these issues will be migrated to the alternative issue type specified in the parameter.",
		[]byte(DeleteIssueType1InputSchema),
	)
}

// DeleteIssueType1Handler is the handler function for the DeleteIssueType1 tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteIssueType1Handler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/rest/api/2/issuetype/{id}", args, []string{"alternativeIssueTypeId", "id"}, contentType, "DeleteIssueType1")
}
