// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteRemoteIssueLinkById tool
const DeleteRemoteIssueLinkByIdInputSchema = "{\n  \"properties\": {\n    \"issueIdOrKey\": {\n      \"description\": \"Issue id or key\",\n      \"type\": \"string\"\n    },\n    \"linkId\": {\n      \"description\": \"Id of the remote issue link\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"issueIdOrKey\",\n    \"linkId\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteRemoteIssueLinkByIdMCPTool creates the MCP Tool instance for DeleteRemoteIssueLinkById
func NewDeleteRemoteIssueLinkByIdMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteRemoteIssueLinkById",
		"Delete remote issue link by id - Delete the remote issue link with the given id on the issue.",
		[]byte(DeleteRemoteIssueLinkByIdInputSchema),
	)
}

// DeleteRemoteIssueLinkByIdHandler is the handler function for the DeleteRemoteIssueLinkById tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteRemoteIssueLinkByIdHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/rest/api/2/issue/{issueIdOrKey}/remotelink/{linkId}", args, []string{"issueIdOrKey", "linkId"}, contentType, "DeleteRemoteIssueLinkById")
}
