// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteProjectRoleActorsFromRole tool
const DeleteProjectRoleActorsFromRoleInputSchema = "{\n  \"properties\": {\n    \"group\": {\n      \"description\": \"If given, removes an actor from given role\",\n      \"type\": \"string\"\n    },\n    \"id\": {\n      \"description\": \"The role id to remove the actors from\",\n      \"format\": \"int64\",\n      \"type\": \"integer\"\n    },\n    \"user\": {\n      \"description\": \"If given, removes an actor from given role\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"id\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the DeleteProjectRoleActorsFromRole tool (Status: 200, Content-Type: application/json)
const DeleteProjectRoleActorsFromRoleResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Returns updated actors list.\n\n## Response Structure\n\n- Structure (Type: object):\n  - **actors** (Type: array):\n    - **Items** (Type: object):\n      - **avatarUrl** (Type: string, uri):\n      - **name** (Type: string):\n          - Example: 'jira-developers'\n"

// NewDeleteProjectRoleActorsFromRoleMCPTool creates the MCP Tool instance for DeleteProjectRoleActorsFromRole
func NewDeleteProjectRoleActorsFromRoleMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteProjectRoleActorsFromRole",
		"Removes default actor from a role - Removes default actor from the given role.",
		[]byte(DeleteProjectRoleActorsFromRoleInputSchema),
	)
}

// DeleteProjectRoleActorsFromRoleHandler is the handler function for the DeleteProjectRoleActorsFromRole tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteProjectRoleActorsFromRoleHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/rest/api/2/role/{id}/actors", args, []string{"id"}, contentType, "DeleteProjectRoleActorsFromRole")
}
