// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteProjectRole tool
const DeleteProjectRoleInputSchema = "{\n  \"properties\": {\n    \"id\": {\n      \"description\": \"The role id\",\n      \"format\": \"int64\",\n      \"type\": \"integer\"\n    },\n    \"swap\": {\n      \"description\": \"If given, removes a role even if it is used in scheme by replacing the role with the given one\",\n      \"format\": \"int64\",\n      \"type\": \"integer\"\n    }\n  },\n  \"required\": [\n    \"id\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteProjectRoleMCPTool creates the MCP Tool instance for DeleteProjectRole
func NewDeleteProjectRoleMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteProjectRole",
		"Deletes a role - Deletes a role. May return 403 in the future",
		[]byte(DeleteProjectRoleInputSchema),
	)
}

// DeleteProjectRoleHandler is the handler function for the DeleteProjectRole tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteProjectRoleHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/rest/api/2/role/{id}", args, []string{"id"}, contentType, "DeleteProjectRole")
}
