// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteSession tool
const DeleteSessionInputSchema = "{\n  \"properties\": {\n    \"username\": {\n      \"description\": \"a String containing username.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"username\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteSessionMCPTool creates the MCP Tool instance for DeleteSession
func NewDeleteSessionMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteSession",
		"Delete user session - Invalidates session of given user.",
		[]byte(DeleteSessionInputSchema),
	)
}

// DeleteSessionHandler is the handler function for the DeleteSession tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteSessionHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/rest/api/2/user/session/{username}", args, []string{"username"}, contentType, "DeleteSession")
}
