// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeletePriorityScheme tool
const DeletePrioritySchemeInputSchema = "{\n  \"properties\": {\n    \"schemeId\": {\n      \"description\": \"Id of priority scheme to delete\",\n      \"format\": \"int64\",\n      \"type\": \"integer\"\n    }\n  },\n  \"required\": [\n    \"schemeId\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeletePrioritySchemeMCPTool creates the MCP Tool instance for DeletePriorityScheme
func NewDeletePrioritySchemeMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeletePriorityScheme",
		"Delete a priority scheme - Deletes a priority scheme. All projects using deleted scheme will use default priority scheme afterwards.",
		[]byte(DeletePrioritySchemeInputSchema),
	)
}

// DeletePrioritySchemeHandler is the handler function for the DeletePriorityScheme tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeletePrioritySchemeHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/rest/api/2/priorityschemes/{schemeId}", args, []string{"schemeId"}, contentType, "DeletePriorityScheme")
}
