// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteProperty5 tool
const DeleteProperty5InputSchema = "{\n  \"properties\": {\n    \"projectIdOrKey\": {\n      \"description\": \"The project from which the property will be removed.\",\n      \"type\": \"string\"\n    },\n    \"propertyKey\": {\n      \"description\": \"The key of the property to remove.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"projectIdOrKey\",\n    \"propertyKey\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteProperty5MCPTool creates the MCP Tool instance for DeleteProperty5
func NewDeleteProperty5MCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteProperty5",
		"Delete property from project - Removes the property from the project identified by the key or by the id.",
		[]byte(DeleteProperty5InputSchema),
	)
}

// DeleteProperty5Handler is the handler function for the DeleteProperty5 tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteProperty5Handler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/rest/api/2/project/{projectIdOrKey}/properties/{propertyKey}", args, []string{"projectIdOrKey", "propertyKey"}, contentType, "DeleteProperty5")
}
