// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteScheme tool
const DeleteSchemeInputSchema = "{\n  \"properties\": {\n    \"id\": {\n      \"description\": \"The id of the scheme.\",\n      \"format\": \"int64\",\n      \"type\": \"integer\"\n    }\n  },\n  \"required\": [\n    \"id\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteSchemeMCPTool creates the MCP Tool instance for DeleteScheme
func NewDeleteSchemeMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteScheme",
		"Delete the specified workflow scheme - Delete the passed workflow scheme.",
		[]byte(DeleteSchemeInputSchema),
	)
}

// DeleteSchemeHandler is the handler function for the DeleteScheme tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteSchemeHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/rest/api/2/workflowscheme/{id}", args, []string{"id"}, contentType, "DeleteScheme")
}
