// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteBoard tool
const DeleteBoardInputSchema = "{\n  \"properties\": {\n    \"boardId\": {\n      \"description\": \"id of the board to be deleted\",\n      \"format\": \"int64\",\n      \"type\": \"integer\"\n    }\n  },\n  \"required\": [\n    \"boardId\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteBoardMCPTool creates the MCP Tool instance for DeleteBoard
func NewDeleteBoardMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteBoard",
		"Delete the board - Deletes the board.",
		[]byte(DeleteBoardInputSchema),
	)
}

// DeleteBoardHandler is the handler function for the DeleteBoard tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteBoardHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/rest/agile/1.0/board/{boardId}", args, []string{"boardId"}, contentType, "DeleteBoard")
}
