// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetAccessibleProjectTypeByKey tool
const GetAccessibleProjectTypeByKeyInputSchema = "{\n  \"properties\": {\n    \"projectTypeKey\": {\n      \"description\": \"The key of the project type\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"projectTypeKey\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetAccessibleProjectTypeByKey tool (Status: 200, Content-Type: application/json)
const GetAccessibleProjectTypeByKeyResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Returns a representation of the project type with the given id\n\n## Response Structure\n\n- Structure (Type: object):\n  - **color** (Type: string):\n      - Example: '#FFFFFF'\n  - **descriptionI18nKey** (Type: string):\n      - Example: 'Project type for software projects'\n  - **formattedKey** (Type: string):\n      - Example: 'Software'\n  - **icon** (Type: string):\n      - Example: 'PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAxOC4xLjEsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iTGF5ZXJfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeD0iMHB4IiB5PSIwcHgiDQoJIHZpZXdCb3g9IjAgMCAzMiAzMiIgZW5hYmxlLWJhY2tncm91bmQ9Im5ldyAwIDAgMzIgMzIiIHhtbDpzcGFjZT0icHJlc2VydmUiPg0KPGc+DQoJPHBhdGggZmlsbD0iIzY2NjY2NiIgZD0iTTE2LDBDNy4yLDAsMCw3LjIsMCwxNmMwLDguOCw3LjIsMTYsMTYsMTZjOC44LDAsMTYtNy4yLDE2LTE2QzMyLDcuMiwyNC44LDAsMTYsMHogTTI1LjcsMjMNCgkJYzAsMS44LTEuNCwzLjItMy4yLDMuMkg5LjJDNy41LDI2LjIsNiwyNC44LDYsMjNWOS44QzYsOCw3LjUsNi42LDkuMiw2LjZoMTMuMmMwLjIsMCwwLjQsMCwwLjcsMC4xbC0yLjgsMi44SDkuMg0KCQlDOSw5LjQsOC44LDkuNiw4LjgsOS44VjIzYzAsMC4yLDAuMiwwLjQsMC40LDAuNGgxMy4yYzAuMiwwLDAuNC0wLjIsMC40LTAuNHYtNS4zbDIuOC0yLjhWMjN6IE0xNS45LDIxLjNMMTEsMTYuNGwyLTJsMi45LDIuOQ0KCQlMMjYuNCw2LjhjMC42LDAuNywxLjIsMS41LDEuNywyLjNMMTUuOSwyMS4zeiIvPg0KPC9nPg0KPC9zdmc+'\n  - **key** (Type: string):\n      - Example: 'software'\n"

// NewGetAccessibleProjectTypeByKeyMCPTool creates the MCP Tool instance for GetAccessibleProjectTypeByKey
func NewGetAccessibleProjectTypeByKeyMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetAccessibleProjectTypeByKey",
		"Get project type by key - Returns the project type with the given key, if it is accessible to the logged in user. This takes into account whether the user is licensed on the Application that defines the project type.",
		[]byte(GetAccessibleProjectTypeByKeyInputSchema),
	)
}

// GetAccessibleProjectTypeByKeyHandler is the handler function for the GetAccessibleProjectTypeByKey tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetAccessibleProjectTypeByKeyHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/rest/api/2/project/type/{projectTypeKey}/accessible", args, []string{"projectTypeKey"}, contentType, "GetAccessibleProjectTypeByKey")
}
