// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetEpics tool
const GetEpicsInputSchema = "{\n  \"properties\": {\n    \"boardId\": {\n      \"description\": \"The Id of the board that contains the requested epics.\",\n      \"format\": \"int64\",\n      \"type\": \"integer\"\n    },\n    \"done\": {\n      \"description\": \"Filters results to epics that are either done or not done. Valid values: true, false.\",\n      \"type\": \"string\"\n    },\n    \"maxResults\": {\n      \"description\": \"The maximum number of epics to return per page. Default: 50. See the 'Pagination' section at the top of this page for more details.\",\n      \"format\": \"int32\",\n      \"type\": \"integer\"\n    },\n    \"startAt\": {\n      \"description\": \"The starting index of the returned epics. Base index: 0. See the 'Pagination' section at the top of this page for more details.\",\n      \"format\": \"int64\",\n      \"type\": \"integer\"\n    }\n  },\n  \"required\": [\n    \"boardId\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetEpics tool (Status: 200, Content-Type: application/json)
const GetEpicsResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Returns the requested epics, at the specified page of the results.\n\n## Response Structure\n\n- Structure (Type: object):\n  - **color** (Type: object):\n      - Example: '\"color_6\"'\n    - **key** (Type: string):\n        - Example: 'ghx-label-1'\n        - Enum: ['color_1', 'color_2', 'color_3', 'color_4', 'color_5', 'color_6', 'color_7', 'color_8', 'color_9', 'color_10', 'color_11', 'color_12', 'color_13', 'color_14']\n  - **done** (Type: boolean):\n      - Example: 'true'\n  - **id** (Type: integer, int64):\n      - Example: '10000'\n  - **key** (Type: string):\n      - Example: 'PR-1'\n  - **name** (Type: string):\n      - Example: 'Epic 1'\n  - **self** (Type: string, uri):\n      - Example: 'http://www.example.com/jira/rest/api/2/issue/10000'\n  - **summary** (Type: string):\n      - Example: 'Epic 1 summary'\n"

// NewGetEpicsMCPTool creates the MCP Tool instance for GetEpics
func NewGetEpicsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetEpics",
		"Get all epics from the board - Returns all epics from the board, for the given board Id. This only includes epics that the user has permission to view. Note, if the user does not have permission to view the board, no epics will be returned at all.",
		[]byte(GetEpicsInputSchema),
	)
}

// GetEpicsHandler is the handler function for the GetEpics tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetEpicsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/rest/agile/1.0/board/{boardId}/epic", args, []string{"boardId"}, contentType, "GetEpics")
}
