// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetIssueSecurityScheme1 tool
const GetIssueSecurityScheme1InputSchema = "{\n  \"properties\": {\n    \"projectKeyOrId\": {\n      \"description\": \"The project id or project key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"projectKeyOrId\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetIssueSecurityScheme1 tool (Status: 200, Content-Type: application/json)
const GetIssueSecurityScheme1ResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Issue security scheme\n\n## Response Structure\n\n- Structure (Type: object):\n  - **defaultSecurityLevelId** (Type: integer, int64):\n      - Example: '10001'\n  - **description** (Type: string):\n      - Example: 'This is a security scheme'\n  - **id** (Type: integer, int64):\n      - Example: '10000'\n  - **levels** (Type: array):\n    - **Items** (Type: object):\n      - **description** (Type: string):\n          - Example: 'This is a security level'\n      - **id** (Type: string):\n          - Example: '10000'\n      - **name** (Type: string):\n          - Example: 'My Security Level'\n      - **self** (Type: string):\n          - Example: 'http://www.example.com/jira/rest/api/2/securitylevel/10000'\n  - **name** (Type: string):\n      - Example: 'My Security Scheme'\n  - **self** (Type: string):\n      - Example: 'http://www.example.com/jira/rest/api/2/issuesecurityschemes/10000'\n"

// NewGetIssueSecurityScheme1MCPTool creates the MCP Tool instance for GetIssueSecurityScheme1
func NewGetIssueSecurityScheme1MCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetIssueSecurityScheme1",
		"Get issue security scheme for project - Returns the issue security scheme for project.",
		[]byte(GetIssueSecurityScheme1InputSchema),
	)
}

// GetIssueSecurityScheme1Handler is the handler function for the GetIssueSecurityScheme1 tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetIssueSecurityScheme1Handler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/rest/api/2/project/{projectKeyOrId}/issuesecuritylevelscheme", args, []string{"projectKeyOrId"}, contentType, "GetIssueSecurityScheme1")
}
