// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetProject1 tool
const GetProject1InputSchema = "{\n  \"properties\": {\n    \"key\": {\n      \"description\": \"The project key\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the GetProject1 tool (Status: 200, Content-Type: application/json)
const GetProject1ResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Returns an ErrorCollection containing any validation errors for the project key. If the project key is valid, the ErrorCollection will be empty.\n\n## Response Structure\n\n- Structure (Type: object):\n  - **errorMessages** (Type: array):\n    - **Items** (Type: string):\n  - **errors** (Type: object):\n    - **Additional Properties**:\n      - **property value** (Type: string):\n"

// NewGetProject1MCPTool creates the MCP Tool instance for GetProject1
func NewGetProject1MCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetProject1",
		"Get project key validation - Validates a project key.",
		[]byte(GetProject1InputSchema),
	)
}

// GetProject1Handler is the handler function for the GetProject1 tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetProject1Handler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/rest/api/2/projectvalidate/key", args, []string{}, contentType, "GetProject1")
}
