// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetPriorities tool
const GetPrioritiesInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the GetPriorities tool (Status: 200, Content-Type: application/json)
const GetPrioritiesResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> List of priorities\n\n## Response Structure\n\n- Structure (Type: object):\n  - **description** (Type: string):\n      - Example: 'This is a description of the priority'\n  - **iconUrl** (Type: string):\n      - Example: 'http://www.example.com/jira/images/icons/priorities/major.png'\n  - **id** (Type: string):\n      - Example: '1'\n  - **name** (Type: string):\n      - Example: 'Major'\n  - **self** (Type: string):\n      - Example: 'http://www.example.com/jira/rest/api/2/priority/1'\n  - **statusColor** (Type: string):\n      - Example: 'red'\n"

// NewGetPrioritiesMCPTool creates the MCP Tool instance for GetPriorities
func NewGetPrioritiesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetPriorities",
		"Get all issue priorities - Returns a list of all issue priorities",
		[]byte(GetPrioritiesInputSchema),
	)
}

// GetPrioritiesHandler is the handler function for the GetPriorities tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetPrioritiesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/rest/api/2/priority", args, []string{}, contentType, "GetPriorities")
}
