// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetProjectVersions tool
const GetProjectVersionsInputSchema = "{\n  \"properties\": {\n    \"expand\": {\n      \"description\": \"Parameters to expand\",\n      \"type\": \"string\"\n    },\n    \"projectIdOrKey\": {\n      \"description\": \"Project id or project key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"projectIdOrKey\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetProjectVersions tool (Status: 200, Content-Type: application/json)
const GetProjectVersionsResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Project versions\n\n## Response Structure\n\n- Structure (Type: object):\n  - **archived** (Type: boolean):\n      - Example: 'false'\n  - **description** (Type: string):\n      - Example: 'An excellent version'\n  - **expand** (Type: string):\n      - Example: '10000'\n  - **id** (Type: string):\n      - Example: '10000'\n  - **moveUnfixedIssuesTo** (Type: string, uri):\n      - Example: 'http://localhost:8090/jira/rest/api/2/version/10000/move'\n  - **name** (Type: string):\n      - Example: 'New Version 1'\n  - **overdue** (Type: boolean):\n      - Example: 'true'\n  - **project** (Type: string):\n      - Example: 'PXA'\n  - **projectId** (Type: integer, int64):\n      - Example: '10000'\n  - **releaseDate** (Type: string, date-time):\n  - **releaseDateSet** (Type: boolean):\n      - Example: 'false'\n  - **released** (Type: boolean):\n      - Example: 'true'\n  - **self** (Type: string, uri):\n      - Example: 'http://localhost:8090/jira/rest/api/2/version/10000'\n  - **startDate** (Type: string, date-time):\n  - **startDateSet** (Type: boolean):\n      - Example: 'false'\n  - **userReleaseDate** (Type: string):\n      - Example: '2012-09-15T21:11:01.834+0000'\n  - **userStartDate** (Type: string):\n      - Example: '2012-08-15T21:11:01.834+0000'\n"

// NewGetProjectVersionsMCPTool creates the MCP Tool instance for GetProjectVersions
func NewGetProjectVersionsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetProjectVersions",
		"Get project versions - Contains a full representation of a the specified project's versions.",
		[]byte(GetProjectVersionsInputSchema),
	)
}

// GetProjectVersionsHandler is the handler function for the GetProjectVersions tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetProjectVersionsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/rest/api/2/project/{projectIdOrKey}/versions", args, []string{"projectIdOrKey"}, contentType, "GetProjectVersions")
}
