// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetStatuses tool
const GetStatusesInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the GetStatuses tool (Status: 200, Content-Type: application/json)
const GetStatusesResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Returns a list of all Jira issue statuses in JSON format, that are visible to the user.\n\n## Response Structure\n\n- Structure (Type: object):\n  - **description** (Type: string):\n      - Example: 'The issue is currently being worked on.'\n  - **iconUrl** (Type: string):\n      - Example: 'http://localhost:8090/jira/images/icons/progress.gif'\n  - **id** (Type: string):\n      - Example: '10000'\n  - **name** (Type: string):\n      - Example: 'In Progress'\n  - **self** (Type: string):\n      - Example: 'http://localhost:8090/jira/rest/api/2.0/status/10000'\n  - **statusCategory** (Type: object):\n    - **colorName** (Type: string):\n        - Example: 'blue-gray'\n    - **id** (Type: integer, int64):\n        - Example: '1'\n    - **key** (Type: string):\n        - Example: 'new'\n    - **name** (Type: string):\n        - Example: 'To Do'\n    - **self** (Type: string):\n        - Example: 'http://localhost:8090/jira/rest/api/2.0/statuscategory/1'\n  - **statusColor** (Type: string):\n      - Example: 'green'\n"

// NewGetStatusesMCPTool creates the MCP Tool instance for GetStatuses
func NewGetStatusesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetStatuses",
		"Get all statuses - Returns a list of all statuses",
		[]byte(GetStatusesInputSchema),
	)
}

// GetStatusesHandler is the handler function for the GetStatuses tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetStatusesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/rest/api/2/status", args, []string{}, contentType, "GetStatuses")
}
