// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PartialUpdateProjectRole tool
const PartialUpdateProjectRoleInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"properties\": {\n        \"description\": {\n          \"example\": \"role description\",\n          \"type\": \"string\"\n        },\n        \"name\": {\n          \"example\": \"MyRole\",\n          \"type\": \"string\"\n        }\n      },\n      \"type\": \"object\"\n    },\n    \"id\": {\n      \"description\": \"The role id\",\n      \"format\": \"int64\",\n      \"type\": \"integer\"\n    }\n  },\n  \"required\": [\n    \"id\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the PartialUpdateProjectRole tool (Status: 200, Content-Type: application/json)
const PartialUpdateProjectRoleResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Returns updated role.\n\n## Response Structure\n\n- Structure (Type: object):\n  - **actors** (Type: array):\n    - **Items** (Type: object):\n      - **avatarUrl** (Type: string, uri):\n      - **name** (Type: string):\n          - Example: 'jira-developers'\n  - **description** (Type: string):\n      - Example: 'A project role that represents developers in a project'\n  - **id** (Type: integer, int64):\n      - Example: '10360'\n  - **name** (Type: string):\n      - Example: 'Developers'\n  - **self** (Type: string, uri):\n      - Example: 'http://www.example.com/jira/rest/api/2/project/MKY/role/10360'\n"

// NewPartialUpdateProjectRoleMCPTool creates the MCP Tool instance for PartialUpdateProjectRole
func NewPartialUpdateProjectRoleMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PartialUpdateProjectRole",
		"Partially updates a role's name or description - Partially updates a roles name or description.",
		[]byte(PartialUpdateProjectRoleInputSchema),
	)
}

// PartialUpdateProjectRoleHandler is the handler function for the PartialUpdateProjectRole tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PartialUpdateProjectRoleHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/rest/api/2/role/{id}", args, []string{"id"}, contentType, "PartialUpdateProjectRole")
}
