// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the RemoveUserFromApplication1 tool
const RemoveUserFromApplication1InputSchema = "{\n  \"properties\": {\n    \"applicationKey\": {\n      \"description\": \"application key\",\n      \"type\": \"string\"\n    },\n    \"username\": {\n      \"description\": \"username\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewRemoveUserFromApplication1MCPTool creates the MCP Tool instance for RemoveUserFromApplication1
func NewRemoveUserFromApplication1MCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"RemoveUserFromApplication1",
		"Remove user from application - Remove user from given application. Admin permission will be required to perform this operation.",
		[]byte(RemoveUserFromApplication1InputSchema),
	)
}

// RemoveUserFromApplication1Handler is the handler function for the RemoveUserFromApplication1 tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func RemoveUserFromApplication1Handler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/rest/api/2/user/application", args, []string{}, contentType, "RemoveUserFromApplication1")
}
