// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the RunUpgradesNow tool
const RunUpgradesNowInputSchema = "{\n  \"type\": \"object\"\n}"

// NewRunUpgradesNowMCPTool creates the MCP Tool instance for RunUpgradesNow
func NewRunUpgradesNowMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"RunUpgradesNow",
		"Run pending upgrade tasks - Runs any pending delayed upgrade tasks. Need Admin permissions to do this.",
		[]byte(RunUpgradesNowInputSchema),
	)
}

// RunUpgradesNowHandler is the handler function for the RunUpgradesNow tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func RunUpgradesNowHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/rest/api/2/upgrade", args, []string{}, contentType, "RunUpgradesNow")
}
