// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the SetBaseUrl tool
const SetBaseUrlInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewSetBaseUrlMCPTool creates the MCP Tool instance for SetBaseUrl
func NewSetBaseUrlMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"SetBaseUrl",
		"Update base URL for Jira instance - Sets the base URL that is configured for this Jira instance.",
		[]byte(SetBaseUrlInputSchema),
	)
}

// SetBaseUrlHandler is the handler function for the SetBaseUrl tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func SetBaseUrlHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/rest/api/2/settings/baseUrl", args, []string{}, contentType, "SetBaseUrl")
}
