// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the SetProperty1_9fc616f7 tool
const SetProperty1_9fc616f7InputSchema = "{\n  \"properties\": {\n    \"propertyKey\": {\n      \"description\": \"The key of the sprint's property. The maximum length of the key is 255 bytes.\",\n      \"type\": \"string\"\n    },\n    \"sprintId\": {\n      \"description\": \"The id of the sprint on which the property will be set.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"propertyKey\",\n    \"sprintId\"\n  ],\n  \"type\": \"object\"\n}"

// NewSetProperty1_9fc616f7MCPTool creates the MCP Tool instance for SetProperty1_9fc616f7
func NewSetProperty1_9fc616f7MCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"SetProperty1_9fc616f7",
		"Update a sprint's property - Sets the value of the specified sprint's property. You can use this resource to store a custom data against the sprint identified by the id. The user who stores the data is required to have permissions to modify the sprint.",
		[]byte(SetProperty1_9fc616f7InputSchema),
	)
}

// SetProperty1_9fc616f7Handler is the handler function for the SetProperty1_9fc616f7 tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func SetProperty1_9fc616f7Handler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/rest/agile/1.0/sprint/{sprintId}/properties/{propertyKey}", args, []string{"propertyKey", "sprintId"}, contentType, "SetProperty1_9fc616f7")
}
