// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the SetPinComment tool
const SetPinCommentInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"description\": \"'true' must be included as raw data\",\n      \"type\": \"boolean\"\n    },\n    \"id\": {\n      \"description\": \"Comment id\",\n      \"type\": \"string\"\n    },\n    \"issueIdOrKey\": {\n      \"description\": \"Issue id or key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"body\",\n    \"id\",\n    \"issueIdOrKey\"\n  ],\n  \"type\": \"object\"\n}"

// NewSetPinCommentMCPTool creates the MCP Tool instance for SetPinComment
func NewSetPinCommentMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"SetPinComment",
		"Pin a comment - Pins a comment to the top of the comment list.",
		[]byte(SetPinCommentInputSchema),
	)
}

// SetPinCommentHandler is the handler function for the SetPinComment tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func SetPinCommentHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/rest/api/2/issue/{issueIdOrKey}/comment/{id}/pin", args, []string{"id", "issueIdOrKey"}, contentType, "SetPinComment")
}
