// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the SetPreference tool
const SetPreferenceInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"type\": \"string\"\n    },\n    \"key\": {\n      \"description\": \"Key of the preference to be set.\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewSetPreferenceMCPTool creates the MCP Tool instance for SetPreference
func NewSetPreferenceMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"SetPreference",
		"Update user preference - Sets preference of the currently logged in user. Preference key must be provided as input parameters (key). Value must be provided as post body. If key or value parameter is not provided - status code 404. If preference is set - status code 204.",
		[]byte(SetPreferenceInputSchema),
	)
}

// SetPreferenceHandler is the handler function for the SetPreference tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func SetPreferenceHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/rest/api/2/mypreferences", args, []string{}, contentType, "SetPreference")
}
