// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the SetReadyToUpgrade tool
const SetReadyToUpgradeInputSchema = "{\n  \"type\": \"object\"\n}"

// NewSetReadyToUpgradeMCPTool creates the MCP Tool instance for SetReadyToUpgrade
func NewSetReadyToUpgradeMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"SetReadyToUpgrade",
		"Start cluster upgrade - Starts the cluster upgrade.",
		[]byte(SetReadyToUpgradeInputSchema),
	)
}

// SetReadyToUpgradeHandler is the handler function for the SetReadyToUpgrade tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func SetReadyToUpgradeHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/rest/api/2/cluster/zdu/start", args, []string{}, contentType, "SetReadyToUpgrade")
}
