// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UnmapAllSprints tool
const UnmapAllSprintsInputSchema = "{\n  \"type\": \"object\"\n}"

// NewUnmapAllSprintsMCPTool creates the MCP Tool instance for UnmapAllSprints
func NewUnmapAllSprintsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UnmapAllSprints",
		"Unmap all sprints from being synced - Sets the Synced flag to false for all sprints on this Jira instance. This operation is intended for cleanup only. It is highly destructive and not reversible. Use with caution.",
		[]byte(UnmapAllSprintsInputSchema),
	)
}

// UnmapAllSprintsHandler is the handler function for the UnmapAllSprints tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UnmapAllSprintsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/rest/agile/1.0/sprint/unmap-all", args, []string{}, contentType, "UnmapAllSprints")
}
