// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UpdateProjectAvatar tool
const UpdateProjectAvatarInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"description\": \"Avatar data\",\n      \"properties\": {\n        \"id\": {\n          \"example\": \"1000\",\n          \"type\": \"string\"\n        },\n        \"owner\": {\n          \"example\": \"fred\",\n          \"type\": \"string\"\n        },\n        \"selected\": {\n          \"type\": \"boolean\"\n        }\n      },\n      \"type\": \"object\"\n    },\n    \"projectIdOrKey\": {\n      \"description\": \"Project id or project key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"body\",\n    \"projectIdOrKey\"\n  ],\n  \"type\": \"object\"\n}"

// NewUpdateProjectAvatarMCPTool creates the MCP Tool instance for UpdateProjectAvatar
func NewUpdateProjectAvatarMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UpdateProjectAvatar",
		"Update project avatar - Updates an avatar for a project. This is step 3/3 of changing an avatar for a project.",
		[]byte(UpdateProjectAvatarInputSchema),
	)
}

// UpdateProjectAvatarHandler is the handler function for the UpdateProjectAvatar tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UpdateProjectAvatarHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/rest/api/2/project/{projectIdOrKey}/avatar", args, []string{"projectIdOrKey"}, contentType, "UpdateProjectAvatar")
}
