// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"jira-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UpdateIssueType tool
const UpdateIssueTypeInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"description\": \"All information about the issue type.\",\n      \"properties\": {\n        \"avatarId\": {\n          \"example\": 1,\n          \"format\": \"int64\",\n          \"type\": \"integer\"\n        },\n        \"description\": {\n          \"example\": \"description\",\n          \"type\": \"string\"\n        },\n        \"name\": {\n          \"example\": \"name\",\n          \"type\": \"string\"\n        }\n      },\n      \"type\": \"object\"\n    },\n    \"id\": {\n      \"description\": \"The issue type id.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"body\",\n    \"id\"\n  ],\n  \"type\": \"object\"\n}"

// NewUpdateIssueTypeMCPTool creates the MCP Tool instance for UpdateIssueType
func NewUpdateIssueTypeMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UpdateIssueType",
		"Update specified issue type from JSON representation - Updates the specified issue type from a JSON representation.",
		[]byte(UpdateIssueTypeInputSchema),
	)
}

// UpdateIssueTypeHandler is the handler function for the UpdateIssueType tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UpdateIssueTypeHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/rest/api/2/issuetype/{id}", args, []string{"id"}, contentType, "UpdateIssueType")
}
